#ifndef CHARMOVE_2_H
#define CHARMOVE_2_H

#include "structs.h"

s32 comm_rapp(WORK* wk, CHAR_CMD* ctc);
s32 comm_rapk(WORK* wk, CHAR_CMD* ctc);
s32 comm_back(WORK*, CHAR_CMD*);
s32 comm_wcne2(WORK* wk, CHAR_CMD* ctc);
s32 comm_wclt2(WORK* wk, CHAR_CMD* ctc);
s32 comm_rapp2(WORK* wk, CHAR_CMD* ctc);
s32 comm_rapk2(WORK* wk, CHAR_CMD* ctc);
s32 comm_abbak(WORK*, CHAR_CMD*);
s32 comm_uhsja(PLW* wk, CHAR_CMD* ctc);
s32 get_comm_if_shot(WORK* wk);
s32 get_comm_if_shot_now(WORK* wk);
s32 get_comm_if_lvsh(WORK* wk);
s32 get_comm_djmp_lever_dir(PLW* wk);
s32 check_cgd_patdat(WORK* wk);
void check_cgd_patdat2(WORK* wk);
u32 check_xcopy_filter_se_req(WORK* wk);
s32 comm_asxy(WORK* wk, CHAR_CMD* ctc);
s32 comm_atmf(PLW* wk, CHAR_CMD* ctc);
s32 comm_ccch(WORK* wk, CHAR_CMD* ctc);
s32 comm_chkwf(PLW* wk, CHAR_CMD* ctc);
s32 comm_emhp(WORK* wk, CHAR_CMD* ctc);
s32 comm_epcy(WORK*, CHAR_CMD*);
s32 comm_flip(WORK* wk, CHAR_CMD* _p1);
s32 comm_iflg(WORK*, CHAR_CMD*);
s32 comm_imgc(PLW* wk, CHAR_CMD* ctc);
s32 comm_ixbw(WORK*, CHAR_CMD*);
s32 comm_mpcy(WORK*, CHAR_CMD*);
s32 comm_mvix(WORK* wk, CHAR_CMD* ctc);
s32 comm_myhp(WORK*, CHAR_CMD*);
s32 comm_retmj(PLW* wk, CHAR_CMD* _p1);
s32 comm_rhsja(PLW* wk, CHAR_CMD* ctc);
s32 comm_rv_x(WORK* wk, CHAR_CMD* ctc);
s32 comm_rv_y(WORK* wk, CHAR_CMD* ctc);
s32 comm_rvxy(WORK* wk, CHAR_CMD* ctc);
s32 comm_s123(WORK* wk, CHAR_CMD* ctc);
s32 comm_s456(WORK* wk, CHAR_CMD* ctc);
s32 comm_schx(WORK*, CHAR_CMD*);
s32 comm_scmd(PLW* wk, CHAR_CMD* ctc);
s32 comm_smhf(WORK* wk, CHAR_CMD* ctc);
s32 comm_srlf(WORK* wk, CHAR_CMD* ctc);
s32 comm_sstx(WORK* wk, CHAR_CMD* ctc);
s32 comm_ssty(WORK*, CHAR_CMD*);
s32 comm_stop(PLW*, CHAR_CMD*);
s32 comm_wadd(WORK* wk, CHAR_CMD* ctc);
s32 comm_wset(WORK*, CHAR_CMD*);
s32 comm_ixfw(WORK* wk, CHAR_CMD* ctc);
s32 comm_quax(WORK* _p0, CHAR_CMD* ctc);
s32 comm_quay(s32 wk_adrs, CHAR_CMD* ctc);
s32 comm_if_s(WORK* wk, CHAR_CMD* ctc);
s32 comm_gets(WORK* wk, CHAR_CMD* ctc);
s32 comm_a123(WORK*, CHAR_CMD*);
s32 comm_a456(WORK*, CHAR_CMD*);
s32 comm_ngme(WORK* wk, CHAR_CMD* ctc);
s32 comm_ngem(WORK* wk, CHAR_CMD* ctc);
s32 comm_iflb(WORK* wk, CHAR_CMD* ctc);
s32 comm_schy(WORK* wk, CHAR_CMD* ctc);
s32 comm_sajp(WORK* wk, CHAR_CMD* ctc);
s32 comm_wswk(WORK* wk, CHAR_CMD* ctc);
s32 comm_wceq(WORK* wk, CHAR_CMD* ctc);
s32 comm_wcne(WORK* wk, CHAR_CMD* ctc);
s32 comm_wcgt(WORK* wk, CHAR_CMD* ctc);
s32 comm_wclt(WORK* wk, CHAR_CMD* ctc);
s32 comm_wadd2(WORK* wk, CHAR_CMD* ctc);
s32 comm_wceq2(WORK* wk, CHAR_CMD* ctc);
s32 comm_wcgt2(WORK* wk, CHAR_CMD* ctc);
s32 comm_imgs(PLW* wk, CHAR_CMD* ctc);
s32 comm_ccfl(PLW* wk, CHAR_CMD* _p1);
u32 comm_exbgs(u32 wk_adrs, CHAR_CMD* ctc, u32 arg2, u32 arg3);
u32 comm_exbgc(WORK* wk);
s32 comm_ngda(WORK* wk, CHAR_CMD* ctc);
s32 comm_kage(WORK* wk, CHAR_CMD* ctc);
s32 comm_dspf(WORK* wk, CHAR_CMD* ctc);
s32 comm_ifrlf(WORK* wk, CHAR_CMD* ctc);
s32 comm_bgrlf(WORK* wk, CHAR_CMD* ctc);
s32 comm_rljmp(WORK* wk, CHAR_CMD* ctc);
s32 comm_ifs2(WORK* wk, CHAR_CMD* ctc);
s32 comm_sse(WORK* wk, CHAR_CMD* ctc);
s32 comm_s_chg(WORK* wk, CHAR_CMD* ctc);
s32 comm_schg2(WORK* wk, CHAR_CMD* ctc);
s32 comm_ifcom(WORK* wk, CHAR_CMD* ctc);
s32 comm_axjmp(WORK* wk, CHAR_CMD* ctc);
s32 comm_ayjmp(WORK* wk, CHAR_CMD* ctc);
s32 comm_ifs3(WORK* wk, CHAR_CMD* ctc);
void set_char_olc_data(WORK* wk);
s32 decord_if_jump(WORK* wk, CHAR_CMD* cpc, s16 ix);
void get_char_data_zanzou(WORK* wk);
s32 get_comm_if_lever(WORK* wk);
s32 get_comm_if_shot_now_off(WORK* wk);
void set_jugde_area(WORK* wk);
void set_new_attnum(WORK* wk);
void kezuri_pow_init(WORK* wk);
void setup_comm_abbak(WORK* wk);
void setup_comm_back(WORK* wk);
void setup_comm_retmj(WORK* wk);

#endif
