#ifndef CMD_MAIN_H
#define CMD_MAIN_H

#include "structs.h"

s32 game_config_menu(void);
void game_config_force_wide(void);
void game_config_screen_item_jp(void);
void game_config_level_item_jp(void);
void game_config_damage_item_jp(void);
void game_config_timer_item_jp(void);
void game_config_event_item_jp(void);
void game_config_bonus_item_jp(void);
s8 game_config_lever_repeat_jp(u16 sw, s16 ix);
void game_config_apply(void);
void game_config_print_value_jp(s16 attr, const TMSCRIPT* script);
void game_config_print_gauge_jp(u32 newv, u32 oldv, s16 attr);
void game_config_print_cursor_jp(const TMSCRIPT* script);
s32 game_config_menu_en(void);
void game_config_init_en(void);
void game_config_screen_item_en(void);
void game_config_level_item_en(void);
void game_config_damage_item_en(void);
void game_config_timer_item_en(void);
void game_config_1p_round_item_en(void);
void game_config_2p_round_item_en(void);
void game_config_event_item_en(void);
void game_config_bonus_item_en(void);
void game_config_exit_item_en(void);
s8 game_config_lever_repeat_en(u16 sw, s16 ix);
void game_config_draw_cursor_en(s16 x);
void game_config_print_gauge_en(u32 x, u32 old_x, s16 attr);
void game_config_print_value_en(s16 attr, const TM_STRING* str);
void debug_menu_player_setup(void);
void debug_menu_select_dispatch(void);
void debug_menu_select_init(void);
void debug_menu_select_run(void);
void debug_object_look_run(void);
void debug_hit_a_judgement_run(void);
void debug_catch_judgment_init(void);
void debug_catch_judgment_run(void);
void debug_char_preview_run(void);
void debug_parts_run(void);
void debug_parts_flip_apply(void);
void debug_char_slot_init(s16 id);
void debug_edit_slots_reset(void);
s32 debug_slot_all_select();
s32 debug_slot_motion_select(void);
s32 debug_check_step(void);
s32 debug_check_rec_step(void);
s32 debug_check_step_z(u16 sw);
s32 debug_check_rec_frame(u16 sw);
s32 debug_flip_cycle(u16 sw);
s32 debug_priority_swap(u16 sw);
void debug_move_record_start(u16 sw);
void debug_record_frame_adjust(u16 sw);
void debug_move_record_menu(void);
void debug_playback_mode_cycle(u16 sw);
void debug_position_by_pad(void);
void debug_bg0_scroll_by_pad(void);
void debug_bg_position_reset(void);
void debug_bg_scroll_by_pad(void);
void debug_hit_box_edit(void);
void debug_set_dummy_box(void);
void debug_set_body_box(s16 n);
void debug_set_hand_box(s16 n);
void debug_set_catch_box(s16 n);
void debug_set_attack_box(s16 n);
void debug_set_hosei_box(s16 n);
void debug_hit_box_cursor(void);
void debug_char_disp(WORK* wk);
void debug_draw_cg_group();
void debug_draw_edit_side(void);
void debug_draw_delta_and_side(void);
s32 debug_cg_group_index();
void debug_draw_cg_data(void);
void screen_work_clear_all(void);
void basic_waza_flag_clear(s16 pl_id);
void check_0(void);
void check_1(void);
void check_10(void);
void check_11(void);
void check_12(void);
void check_13(void);
void check_14(void);
void check_15(void);
void check_16(void);
void check_18(void);
void check_19(void);
void check_2(void);
void check_20(void);
void check_21(void);
void check_22(void);
void check_23(void);
void check_24(void);
void check_25(void);
void check_26(void);
void check_3(void);
void check_4(void);
void check_5(void);
void check_6(void);
void check_6_sub1(void);
void check_6_sub2(void);
void check_7(void);
void check_9(void);
void check_init(void);
void check_next(void);
void cmd_data_set(PLW* , s16 i);
void cmd_init(PLW* pl);
void cmd_move(void);
void command_ok(void);
void command_ok_move(s16 waza_num);
void game_config_init_jp(void);
void game_config_1p_round_item_jp(void);
void game_config_2p_round_item_jp(void);
void game_config_exit_item_jp(void);
void dash_flag_clear(s16 pl_id);
s8 dead_lvr_check(void);
void debug_bg_alloc_init(void);
void debug_bg_tile_put(s16 bg, s32 ofs, s32 page, s32 src);
void debug_bg_alloc_scene_init(void);
void debug_bg_select_dispatch(void);
void debug_bg_select_init(void);
void debug_bg_select_navigate_updown(void);
void debug_object_look_dispatch(void);
void debug_both_players_reset(void);
void debug_char_init(void);
void debug_char_preview_dispatch(void);
void debug_char_preview_init(void);
void debug_char_table_load(void);
void debug_pattern_timer_update(void);
s16 debug_cg_bank_kind(u16 code);
void debug_clear_rgb_triplet_table(void);
void debug_copy_player_snapshot(SNAPSHOT* src, SNAPSHOT* dst);
void debug_draw_record_info(void);
void debug_draw_kakusyuku_frame_flags(void);
void debug_draw_cgd_info(void);
void debug_draw_parts_info(void);
void debug_draw_hit_edit_info(void);
void debug_draw_object_info(void);
void debug_draw_att_data(void);
void debug_draw_cm_data(void);
void debug_draw_position_delta(void);
void debug_draw_cg_group_offset();
void debug_hit_a_print_pattern_rows(WORK* wk, GRID_REC* recs);
void debug_hit_a_print_hit_ix_rows(WORK* wk, GRID9_REC* recs);
u32 debug_held_pad_repeat(u16 sw_now, u16 sw_old, u16 mask, u16 ix);
s32 debug_hex4_to_bcd(s16 x);
u32 debug_hit_a_judgement_alloc_slot(u32 *slot);
void debug_hit_a_judgement_build_table(void);
void debug_hit_a_judgement_cleanup(void);
s32 debug_hit_a_judgement_column_nav(WORK* wk);
s32 debug_hit_a_judgement_edit_grid(WORK* wk);
s32 debug_hit_a_judgement_edit_step(void);
s16 debug_hit_a_judgement_held_step(void);
void debug_hit_a_judgement_init(void);
void debug_hit_a_judgement_navigate_xy(WORK* wk);
void debug_hit_a_draw_cursor(s16 col, s16 flags);
void debug_hit_a_print_counts(WORK* wk);
void debug_hit_a_judgement_print_footer(void);
void debug_catch_judgment_dispatch(void);
void debug_hit_judgment_redraw(void);
void debug_hit_a_exit_confirm(void);
void debug_catch_judgment_input(void);
void debug_hit_judgment_dispatch(void);
void debug_player_color_next(void);
void debug_hit_judgment_init(void);
void debug_zoom_out_by_dipsw(void);
void debug_draw_record_ghosts(void);
void debug_char_disp_once(WORK* wk);
void debug_hit_judgment_input(void);
void debug_edit_pattern_timer_update(void);
void debug_hit_judgment_move(void);
void debug_kakusyuku_input(void);
u32 debug_edit_common_input(void);
void debug_parts_input(void);
s32 debug_parts_flip_cycle(u16 sw);
void debug_cg_number_browse(void);
void debug_char_scale_by_pad(void);
void debug_screen_zoom_by_pad(void);
void debug_cmd_panel_run(void);
void debug_kakusyuku_mode_cycle(u16 sw);
void debug_slot_char_load(void);
void debug_slot_char_load_keep_col(void);
void debug_hud_mode_dispatch(void);
void debug_main_dispatch(void);
s32 debug_memcmp_u32(u32* a, u32* b, s16 n);
void debug_memcpy_u16(u16* src, u16* dst, s16 n);
s32 debug_menu_exit_check(void);
s16 debug_catch_move_record(SNAPSHOT* p1, SNAPSHOT* p2);
void debug_move_snapshot_frame(SNAPSHOT* s, WORK* wk, s16 priority);
void debug_parts_disp(void);
void debug_object_edit_all_char_dispatch(void);
void debug_object_edit_all_char_init(void);
void debug_edit_all_char_input(void);
void debug_object_edit_all_char_move(void);
void debug_object_edit_dispatch(void);
void debug_object_edit_init(void);
void debug_object_edit_input(void);
void debug_object_edit_move(void);
void debug_record_frame_save(void);
void debug_object_edit_snapshot_restore(void);
void debug_object_look_init(void);
void debug_object_look_input(void);
void debug_p1_reset(void);
void debug_parts_copy_overlap(void);
void debug_parts_dispatch(void);
void debug_parts_init(void);
void debug_pattern_edit_init_counts(void);
void debug_pattern_entry_copy_dual(s16 n, s16 box);
void debug_pattern_list_build(void);
void debug_pattern_count(void);
u32 debug_pattern_preview_step(WORK* wk);
void debug_motion_list_count(void);
void debug_bg_color_preset_next(void);
void debug_hit_a_print_box_values(WORK* wk);
void debug_draw_cm_summary(void);
void debug_restore_player_snapshot(SNAPSHOT* rec, WORK* wk);
void debug_snapshot_to_ghost(WORK* wk, SNAPSHOT* rec);
void debug_rgb_editor_navigate(s16 mode);
void debug_rgb_editor_print(s16 print);
s32 debug_lever_repeat_fast(u16 sw, u16 old, u16 mask, s16 ix);
void debug_save_player_snapshot(SNAPSHOT* rec, WORK* wk);
s32 debug_scene_outer_dispatch(void);
void debug_effect_move_all(void);
void debug_menu_work_init(void);
void debug_menu_gfx_load(void);
void debug_bg_stage_load(void);
void debug_ghost_shift_up(WORK* wk);
void debug_ghost_shift_left(WORK* wk);
void debug_ghost_shift_right(WORK* wk);
void debug_hit_box_copy(void);
void debug_set_all_boxes(s16 n);
void debug_set_caught_box(s16 n);
void hi_jump_flag_clear(s16 pl_id);
void key_thru(PLW* pl);
void game_config_move_jp(void);
void game_config_cursor_move_jp(void);
s32 paring_miss_init(void);
void pl_lvr_set(void);
void game_config_move_en(void);
void game_config_cursor_move_en(void);
void sw_pick_up(void);
s32 debug_lever_repeat();
void waza_check(PLW* pl);
void waza_compel_all_init(PLW* pl);
void waza_compel_init(s16 pl_id, s16 num, intptr_t* adrs);
void waza_flag_clear_only_1(s16 pl_id, s16 wznum);

#endif
