#ifndef COM_SUB_H
#define COM_SUB_H

#include "structs.h"

void Adjust_Attack();
void Approach_Walk();
void Branch_Unit_Area();
void Branch_Wait_Area();
s32 Check_Air_Guard(PLW* wk);
s32 Check_Arrival();
void Check_BOSS();
void Check_BOSS_EX();
s32 Check_Behind(PLW* wk, WORK_Other* tmw);
s32 Check_Com_Add_Y();
s32 Check_Dash_Hit();
s32 Check_Diagonal_Shell(PLW* wk);
s32 Check_Dramatic();
s32 Check_Drop_Term();
void Check_EX();
s32 Check_Exit_DENJIN(PLW* wk);
s32 Check_Exit_Guard();
s32 Check_Exit_Term();
void Check_First_Menu(PLW* wk);
s32 Check_Flip_Tech(WORK* em);
s32 Check_Flip_Term(PLW* wk);
s32 Check_Guard(PLW* wk);
s32 Check_Hit_Shell();
s32 Check_Ignore_Shell(WORK_Other* tmw);
s32 Check_Ignore_Shell2(WORK_Other* tmw);
s32 Check_Landed();
s32 Check_Makoto(PLW* wk);
s32 Check_Meoshi_Attack();
s32 Check_Passive(PLW* wk);
void Check_Rapid();
s32 Check_Rapid_End(PLW* wk);
s32 Check_Resume_Lever(PLW* wk);
void Check_SA();
s32 Check_SA_Active();
void Check_SA_Full();
void Check_SA_Range();
s32 Check_SHINRYU(PLW* wk);
s32 Check_SP_Jump_Attack();
s32 Check_Shell(PLW* wk);
s32 Check_Start_Command_Attack();
s32 Check_Start_Hi_Jump(PLW* wk);
s32 Check_Start_Lever_Attack();
s32 Check_Start_Normal_Attack();
s32 Check_Store_Direction();
void Check_Store_Lever();
s32 Check_Term_ABS_Distance(PLW* wk);
s32 Check_Term_Sub();
s32 Check_Term_Sub_Air();
s32 Check_Term_Sub_Y();
s32 Check_VS_Air_Attack();
s32 Ck_Area(PLW* wk);
s32 Ck_Area_Shell(PLW* wk);
void Ck_Distance(PLW* wk);
s32 Ck_Distance_Height(PLW* wk);
void Ck_Distance_Lv(PLW* wk);
void Ck_Distance_LvJ(PLW* wk);
s32 Ck_Distance_XX(PLW* wk);
s32 Ck_Distance_Wall(PLW* wk);
void Com_Random_Select();
void Command_Attack();
s32 Command_Type_00();
s32 Command_Type_01();
s32 Command_Type_06();
s32 Compute_Hit_Time(PLW* wk, WORK_Other* tmw);
s32 Correct_Unit_PL(PLW* wk);
s32 DENJIN_Check();
void Decide_Follow_Menu(PLW* wk);
s32 Decide_Shell_Guard(PLW* wk, WORK_Other* tmw);
s32 Decide_Shell_Reaction();
void Devide_Level();
void EM_Term();
void ETC_Term();
s32 ETC_Term_0000(PLW* wk, WORK* em);
s32 ETC_Term_0002(PLW* wk, WORK* em);
s32 ETC_Term_0003(PLW* wk, WORK* em);
s32 ETC_Term_0004(PLW* wk, WORK* em);
s32 ETC_Term_0005(PLW* wk, WORK* em);
s32 ETC_Term_0006(PLW* wk, WORK* em);
void End_Pattern();
s32 Exit_Term_0000(PLW* wk, WORK* em);
s32 Exit_Term_0001(PLW* wk, WORK* em);
s32 Exit_Term_0002(PLW* wk, WORK* em);
s32 Exit_Term_0003(PLW* wk, WORK* em);
s32 Exit_Term_0004(PLW* wk, WORK* em);
s32 Exit_Term_0005(PLW* wk, WORK* em);
s32 Exit_Term_0006(PLW* wk, WORK* em);
s32 Exit_Term_0007(PLW* wk, WORK* em);
s32 Exit_Term_0008(PLW* wk, WORK* em);
void Approach_Until_Landed();
s32 Check_Wait_Term();
void Jump_Air_Guard();
s32 Check_Stock_Hit_Menu();
void Check_Bullet_Counter(PLW* wk);
s32 Flip_Term_Correct(PLW* wk);
void Forced_Guard();
s32 Get_Meoshi_Data(PLW* wk);
void Guard_or_Jump_VS_Shell();
s32 Hadou_Check();
void Hi_Jump();
void Hi_Jump_Attack();
void Hi_Jump_Attack_Term();
void Hi_Jump_Command_Attack_Term();
void J_Command_Attack();
void Jump();
void Jump_Attack();
void Jump_Attack_Term();
void Jump_Command_Attack_Term();
void Jump_Init();
void Keep_Away();
void Keep_Status();
void Lever_Attack();
void Lever_Attack_SP();
void Lever_Off(PLW* wk);
void Lever_On();
void Look();
void Next_Another_Menu();
void Next_Be_Flip();
void Next_Be_Guard();
void Next_Be_Passive();
void Next_Be_Shell_Guard(PLW* wk, WORK* tmw);
s32 Next_End(PLW* wk);
void Normal_Attack();
void Normal_Attack_SP();
void ORO_HJA_Term();
void ORO_HJCA_Term();
void ORO_JA_Term();
void ORO_JCA_Term();
void Only_Shot();
void Pierce_On(PLW* wk);
void Pierce_Off(PLW* wk);
void Pierce_Off_2(PLW* wk);
void Provoke();
void Push_Shot();
void Rapid_Command_Attack();
void Rapid_Sub(PLW* wk);
void Reaction_Exit_Sub(PLW* wk);
void Reaction_Sub();
s32 SA_Range_Check();
void SA_Term();
void SHELL_Term();
void Search_Back_Term();
void Select_Active(PLW* wk);
s32 Select_Combo_Speed(PLW* wk);
s32 Select_Passive(PLW* wk);
s32 Select_Reflection_Time(PLW* wk);
void Setup_Command_01(PLW* wk);
void Setup_DENJIN_LEVEL(PLW* wk);
s32 Setup_EM_Rank_Index(PLW* wk);
void Setup_Follow();
s32 Setup_Front_or_Back();
s32 Setup_Guard_Lever();
void Setup_KA_Jump(PLW* wk);
void Setup_KA_Walk(PLW* wk);
s32 Setup_LP_Data(PLW* wk);
void Setup_Lever_LR();
s32 Setup_Lv04();
s32 Setup_Lv08();
s32 Setup_Lv10();
s32 Setup_Lv18();
void Setup_Random(PLW* wk);
void Setup_Rapid_End_Term();
s32 Setup_Rapid_Time();
void Setup_Shell_Disposal(PLW* wk, WORK_Other* tmw);
s32 Setup_VS_Catch_Data(PLW* wk);
s32 Setup_WT_Data(PLW* wk);
void Short_Range_Attack();
s32 Small_Jump_Measure(PLW* wk);
void Turn_Over_On(PLW* wk);
s32 VS_Jump_Guard(PLW* wk);
s32 VS_Jump_Term();
void Wait();
void Wait_Attack_Complete();
void Wait_Get_Up();
void Wait_Lie();
void Walk();
s32 YAGYOU_Check();
s32 ETC_Term_0001(PLW* wk, WORK* em);
s32 Check_After_Attack(PLW* wk, WORK* em, s16 VS_Technique);
s32 Check_Attack_Direction(PLW* wk, WORK* em);
s32 Check_Special_Tech_ID(PLW* wk, WORK* em, s16 VS_Technique, u8 SP_Tech_ID, s16 Option);
s32 Check_Blow_Off(PLW* wk, WORK* em, s16 VS_Technique);
s32 Check_Catch(PLW* wk, WORK* em, s16 VS_Technique);
s32 Check_Dash(PLW* wk, WORK* em, s16 VS_Technique);
s32 Check_Faint(PLW* wk, PLW* enemy, s16 VS_Technique);
s32 Check_VS_Jump();
s32 Check_Lie(PLW* wk);
s32 Check_Limited_Jump_Attack(PLW* wk, WORK* em, u8 PL_Status, s8 Status_00);
s32 limited_jump_attack_set(PLW* wk, WORK* em, s16 VS_Technique);
s32 Ck_Passive_Term(PLW* wk);
s32 Check_PL_Unit_A(PLW* wk);
s32 Check_PL_Unit_AS(PLW* wk);
s32 Check_PL_Unit_B(PLW* wk);
s32 Check_PL_Unit_BS(PLW* wk);
s32 Check_PL_Unit_C(PLW* wk);
s32 Check_PL_Unit_CS(PLW* wk);
s32 Check_PL_Unit_D(PLW* wk);
s32 Check_PL_Unit_DS(PLW* wk);
s32 VS_GILL_DS(PLW* wk);
s32 VS_ALEX_DS(PLW* wk);
s32 VS_GILL_D(PLW* wk);
s32 VS_ALEX_D(PLW* wk);
s32 Check_Personal_Action(PLW* wk, WORK* em);
s32 Check_Rolling(PLW* wk, WORK* em);
s32 Check_Limited_Attack(PLW* wk, WORK* em, s16 VS_Technique, u8 PL_Status, s8 Status_00, s16 Limit_Number);
s32 Check_Specific_Term(PLW* wk, WORK* em, s16 VS_Technique, u8 Status_00, u8 Status_01, u8 Status_02);
s32 Check_Stand(PLW* wk, WORK* em, s16 VS_Technique);
s32 Check_Thrown(PLW* wk, WORK* em);
s32 Check_VS_Squat(PLW* wk, WORK* em, s16 VS_Technique, u8 Status_00, u8 Status_01);
s32 Check_Jump_Counter(PLW* wk, PLW* em, s16 Option, s16 Height);
s32 Check_Turn_Over(PLW* wk, WORK* em, s16 VS_Technique);
s32 Check_Lie_Reset(PLW* wk);
s32 Check_Down_Term(PLW* wk);
s32 Check_F_Cross_Chop(PLW* wk, WORK* em, s16 VS_Technique);
s32 VS_ALEX_AS(PLW* wk);
s32 VS_RYU_AS(PLW* wk);
s32 VS_YUN_AS(PLW* wk);
s32 VS_NECRO_AS(PLW* wk);
s32 VS_ORO_AS(PLW* wk);
s32 VS_SEAN_AS(PLW* wk);
s32 VS_URIEN_AS(PLW* wk);
s32 VS_REMY_AS(PLW* wk);
s32 VS_GILL_A(PLW* wk);
s32 VS_ALEX_A(PLW* wk);
s32 VS_YUN_A(PLW* wk);
s32 VS_DUDLEY_A(PLW* wk);
s32 VS_NECRO_A(PLW* wk);
s32 VS_Q_A(PLW* wk);
s32 VS_GILL_BS(PLW* wk);
s32 VS_IBUKI_BS(PLW* wk);
s32 VS_ELENA_BS(PLW* wk);
s32 VS_KEN_BS(PLW* wk);
s32 VS_SEAN_BS(PLW* wk);
s32 VS_URIEN_BS(PLW* wk);
s32 VS_REMY_BS(PLW* wk);
s32 VS_NECRO_B(PLW* wk);
s32 VS_HUGO_B(PLW* wk);
s32 VS_MAKOTO_B(PLW* wk);
s32 VS_REMY_B(PLW* wk);
s32 VS_GILL_CS(PLW* wk);
s32 VS_IBUKI_CS(PLW* wk);
s32 VS_ORO_CS(PLW* wk);
s32 VS_SEAN_CS(PLW* wk);
s32 VS_URIEN_CS(PLW* wk);
s32 VS_CHUN_LI_CS(PLW* wk);
s32 VS_MAKOTO_CS(PLW* wk);
s32 VS_Q_CS(PLW* wk);
s32 VS_NO12_CS(PLW* wk);
s32 VS_IBUKI_C(PLW* wk);
s32 VS_KEN_C(PLW* wk);
s32 VS_SEAN_C(PLW* wk);
s32 VS_MAKOTO_C(PLW* wk);
s32 VS_RYU_DS(PLW* wk);
s32 VS_YUN_DS(PLW* wk);
s32 VS_DUDLEY_DS(PLW* wk);
s32 VS_NECRO_DS(PLW* wk);
s32 VS_IBUKI_DS(PLW* wk);
s32 VS_HUGO_DS(PLW* wk);
s32 VS_NO12_D(PLW* wk);
s32 VS_REMY_D(PLW* wk);
s32 GILL_vs(PLW* wk);
void Setup_Com_Max_Range(void);
s32 Setup_Next_Squat_Timer(PLW* wk);
s32 Setup_Next_Stand_Timer(PLW* wk);
s32 VS_ALEX_B(PLW* wk);
s32 VS_ALEX_BS(PLW* wk);
s32 VS_ALEX_C(PLW* wk);
s32 VS_ALEX_CS(PLW* wk);
s32 VS_CHUN_LI_A(PLW* wk);
s32 VS_MAKOTO_A(PLW* wk);
s32 VS_CHUN_LI_B(PLW* wk);
s32 VS_CHUN_LI_BS(PLW* wk);
s32 VS_CHUN_LI_C(PLW* wk);
s32 VS_DUDLEY_AS(PLW* wk);
s32 VS_DUDLEY_B(PLW* wk);
s32 VS_DUDLEY_BS(PLW* wk);
s32 VS_NECRO_BS(PLW* wk);
s32 VS_DUDLEY_C(PLW* wk);
s32 VS_DUDLEY_CS(PLW* wk);
s32 VS_NECRO_CS(PLW* wk);
s32 VS_ELENA_A(PLW* wk);
s32 VS_ELENA_AS(PLW* wk);
s32 VS_ELENA_B(PLW* wk);
s32 VS_ELENA_CS(PLW* wk);
s32 VS_ELENA_C(PLW* wk);
s32 VS_ELENA_D(PLW* wk);
s32 VS_ELENA_DS(PLW* wk);
s32 VS_ORO_DS(PLW* wk);
s32 VS_KEN_DS(PLW* wk);
s32 VS_SEAN_DS(PLW* wk);
s32 VS_URIEN_DS(PLW* wk);
s32 VS_GOUKI_DS(PLW* wk);
s32 VS_CHUN_LI_DS(PLW* wk);
s32 VS_MAKOTO_DS(PLW* wk);
s32 VS_Q_DS(PLW* wk);
s32 VS_ORO_D(PLW* wk);
s32 VS_KEN_D(PLW* wk);
s32 VS_SEAN_D(PLW* wk);
s32 VS_GILL_AS(PLW* wk);
s32 VS_GILL_B(PLW* wk);
s32 VS_GILL_C(PLW* wk);
s32 VS_GOUKI_A(PLW* wk);
s32 VS_GOUKI_AS(PLW* wk);
s32 VS_CHUN_LI_AS(PLW* wk);
s32 VS_MAKOTO_AS(PLW* wk);
s32 VS_GOUKI_B(PLW* wk);
s32 VS_GOUKI_BS(PLW* wk);
s32 VS_GOUKI_C(PLW* wk);
s32 VS_GOUKI_CS(PLW* wk);
s32 VS_HUGO_A(PLW* wk);
s32 VS_HUGO_AS(PLW* wk);
s32 VS_HUGO_BS(PLW* wk);
s32 VS_HUGO_C(PLW* wk);
s32 VS_HUGO_CS(PLW* wk);
s32 VS_IBUKI_A(PLW* wk);
s32 VS_IBUKI_AS(PLW* wk);
s32 VS_IBUKI_B(PLW* wk);
s32 VS_KEN_A(PLW* wk);
s32 VS_KEN_AS(PLW* wk);
s32 VS_KEN_B(PLW* wk);
s32 VS_KEN_CS(PLW* wk);
s32 VS_MAKOTO_BS(PLW* wk);
s32 VS_NECRO_C(PLW* wk);
s32 VS_NO12_B(PLW* wk);
s32 VS_ORO_B(PLW* wk);
s32 VS_NO12_DS(PLW* wk);
s32 VS_REMY_DS(PLW* wk);
s32 VS_ORO_A(PLW* wk);
s32 VS_ORO_BS(PLW* wk);
s32 VS_ORO_C(PLW* wk);
s32 VS_Q_AS(PLW* wk);
s32 VS_NO12_AS(PLW* wk);
s32 VS_Q_B(PLW* wk);
s32 VS_Q_BS(PLW* wk);
s32 VS_NO12_BS(PLW* wk);
s32 VS_Q_C(PLW* wk);
s32 VS_REMY_A(PLW* wk);
s32 VS_REMY_C(PLW* wk);
s32 VS_REMY_CS(PLW* wk);
s32 VS_RYU_A(PLW* wk);
s32 VS_RYU_B(PLW* wk);
s32 VS_RYU_BS(PLW* wk);
s32 VS_RYU_C(PLW* wk);
s32 VS_RYU_CS(PLW* wk);
s32 VS_RYU_D(PLW* wk);
s32 VS_YUN_D(PLW* wk);
s32 VS_DUDLEY_D(PLW* wk);
s32 VS_NECRO_D(PLW* wk);
void VS_HUGO_D(PLW* wk);
s32 VS_IBUKI_D(PLW* wk);
s32 VS_SEAN_A(PLW* wk);
s32 VS_SEAN_B(PLW* wk);
s32 VS_NO12_A(PLW* wk);
s32 VS_NO12_C(PLW* wk);
s32 VS_URIEN_A(PLW* wk);
s32 VS_URIEN_B(PLW* wk);
s32 VS_URIEN_C(PLW* wk);
s32 VS_URIEN_D(PLW* wk);
s32 VS_GOUKI_D(PLW* wk);
s32 VS_CHUN_LI_D(PLW* wk);
s32 VS_MAKOTO_D(PLW* wk);
s32 VS_Q_D(PLW* wk);
s32 VS_YUN_B(PLW* wk);
s32 VS_YUN_BS(PLW* wk);
s32 VS_YUN_C(PLW* wk);
s32 VS_YUN_CS(PLW* wk);
s32 ETC_Term_0007(PLW* wk, WORK* em);
s32 ETC_Term_0008(PLW* wk);
s32 ETC_Term_0009(PLW* wk);
s32 KEN_vs(PLW* wk);
s32 HUGO_vs(PLW* wk);

#endif
