#ifndef COM_SUB_H
#define COM_SUB_H

#include "structs.h"

void Adjust_Attack();
void Approach_Walk();
void Branch_Unit_Area();
void Branch_Wait_Area();
s32 Check_Air_Guard(PLW* wk);
s32 Check_Arrival();
void Check_BOSS();
void Check_BOSS_EX();
s32 Check_Behind(PLW* wk, WORK_Other* tmw);
s32 Check_Com_Add_Y();
s32 Check_Dash_Hit();
s32 Check_Diagonal_Shell(PLW* wk);
s32 Check_Dramatic();
s32 Check_Drop_Term();
void Check_EX();
s32 Check_Exit_DENJIN(PLW* wk);
s32 Check_Exit_Guard();
s32 Check_Exit_Term();
void Check_First_Menu(PLW* wk);
s32 Check_Flip_Tech(WORK* em);
s32 Check_Flip_Term(PLW* wk);
s32 Check_Guard(PLW* wk);
s32 Check_Hit_Shell();
s32 Check_Ignore_Shell(WORK_Other* tmw);
s32 Check_Ignore_Shell2(WORK_Other* tmw);
s32 Check_Landed();
s32 Check_Makoto(PLW* wk);
s32 Check_Meoshi_Attack();
s32 Check_Passive(PLW* wk);
void Check_Rapid();
s32 Check_Rapid_End(PLW* wk);
s32 Check_Resume_Lever(PLW* wk);
s32 Check_SA();
s32 Check_SA_Active();
void Check_SA_Full();
void Check_SA_Range();
s32 Check_SHINRYU(PLW* wk);
s32 Check_SP_Jump_Attack();
s32 Check_Shell(PLW* wk);
s32 Check_Start_Command_Attack();
s32 Check_Start_Hi_Jump(PLW* wk);
s32 Check_Start_Lever_Attack();
s32 Check_Start_Normal_Attack();
s32 Check_Store_Direction();
void Check_Store_Lever();
s32 Check_Term_ABS_Distance(PLW* wk);
s32 Check_Term_Sub();
s32 Check_Term_Sub_Air();
s32 Check_Term_Sub_Y();
s32 Check_VS_Air_Attack();
s32 Ck_Area(PLW* wk);
s32 Ck_Area_Shell(PLW* wk);
void Ck_Distance(PLW* wk);
s32 Ck_Distance_Height(PLW* wk);
void Ck_Distance_Lv(PLW* wk);
void Ck_Distance_LvJ(PLW* wk);
s32 Ck_Distance_XX(PLW* wk);
s32 Ck_Distance_Wall(PLW* wk);
void Com_Random_Select();
void Command_Attack();
s32 Command_Type_00();
s32 Command_Type_01();
s32 Command_Type_06();
s32 Compute_Hit_Time(PLW* wk, WORK_Other* tmw);
s32 Correct_Unit_PL(PLW* wk);
s32 DENJIN_Check();
void Decide_Follow_Menu(PLW* wk);
s32 Decide_Shell_Guard(PLW* wk, WORK_Other* tmw);
s32 Decide_Shell_Reaction();
void Devide_Level();
void EM_Term();
void ETC_Term();
s32 ETC_Term_0000(PLW* wk, WORK* em);
s32 ETC_Term_0002(PLW* wk, WORK* em);
s32 ETC_Term_0003(PLW* wk, WORK* em);
s32 ETC_Term_0004(PLW* wk, WORK* em);
s32 ETC_Term_0005(PLW* wk, WORK* em);
s32 ETC_Term_0006(PLW* wk, WORK* em);
void End_Pattern();
s32 Exit_Term_0000(PLW* wk, WORK* em);
s32 Exit_Term_0001(PLW* wk, WORK* em);
s32 Exit_Term_0002(PLW* wk, WORK* em);
s32 Exit_Term_0003(PLW* wk, WORK* em);
s32 Exit_Term_0004(PLW* wk, WORK* em);
s32 Exit_Term_0005(PLW* wk, WORK* em);
s32 Exit_Term_0006(PLW* wk, WORK* em);
s32 Exit_Term_0007(PLW* wk, WORK* em);
s32 Exit_Term_0008(PLW* wk, WORK* em);
void Approach_Until_Landed();
s32 Check_Wait_Term();
void Jump_Air_Guard();
s32 Check_Stock_Hit_Menu();
void Check_Bullet_Counter(PLW* wk);
s32 Flip_Term_Correct(PLW* wk);
void Forced_Guard();
s32 Get_Meoshi_Data(PLW* wk);
void Guard_or_Jump_VS_Shell();
s32 Hadou_Check();
void Hi_Jump();
void Hi_Jump_Attack();
void Hi_Jump_Attack_Term();
void Hi_Jump_Command_Attack_Term();
void J_Command_Attack();
void Jump();
void Jump_Attack();
void Jump_Attack_Term();
void Jump_Command_Attack_Term();
void Jump_Init();
void Keep_Away();
void Keep_Status();
void Lever_Attack();
void Lever_Attack_SP();
void Lever_Off(PLW* wk);
void Lever_On();
void Look();
void Next_Another_Menu();
void Next_Be_Flip();
void Next_Be_Guard();
void Next_Be_Passive();
void Next_Be_Shell_Guard(PLW* wk, WORK* tmw);
s32 Next_End(PLW* wk);
void Normal_Attack();
void Normal_Attack_SP();
void ORO_HJA_Term();
void ORO_HJCA_Term();
void ORO_JA_Term();
void ORO_JCA_Term();
void Only_Shot();
void Pierce_On(PLW* wk);
void Pierce_Off(PLW* wk);
void Pierce_Off_2(PLW* wk);
void Provoke();
void Push_Shot();
void Rapid_Command_Attack();
void Rapid_Sub(PLW* wk);
void Reaction_Exit_Sub(PLW* wk);
void Reaction_Sub();
s32 SA_Range_Check();
void SA_Term();
void SHELL_Term();
void Search_Back_Term();
void Select_Active(PLW* wk);
s32 Select_Combo_Speed(PLW* wk);
s32 Select_Passive(PLW* wk);
s32 Select_Reflection_Time(PLW* wk);
void Setup_Command_01(PLW* wk);
void Setup_DENJIN_LEVEL(PLW* wk);
s32 Setup_EM_Rank_Index(PLW* wk);
void Setup_Follow();
s32 Setup_Front_or_Back();
s32 Setup_Guard_Lever();
void Setup_KA_Jump(PLW* wk);
void Setup_KA_Walk(PLW* wk);
s32 Setup_LP_Data(PLW* wk);
void Setup_Lever_LR();
s32 Setup_Lv04();
s32 Setup_Lv08();
s32 Setup_Lv10();
s32 Setup_Lv18();
void Setup_Random(PLW* wk);
void Setup_Rapid_End_Term();
s32 Setup_Rapid_Time();
void Setup_Shell_Disposal(PLW* wk, WORK_Other* tmw);
s32 Setup_VS_Catch_Data(PLW* wk);
s32 Setup_WT_Data(PLW* wk);
void Short_Range_Attack();
s32 Small_Jump_Measure(PLW* wk);
void Turn_Over_On(PLW* wk);
void VS_Jump_Guard(PLW* wk);
s32 VS_Jump_Term();
void Wait();
void Wait_Attack_Complete();
void Wait_Get_Up();
void Wait_Lie();
void Walk();
s32 YAGYOU_Check();
s32 ETC_Term_0001(PLW* wk, WORK* em);

#endif
