#ifndef MANAGE_H
#define MANAGE_H

#include "structs.h"

void Additional_Bonus(s16 PL_id);
u32 Setup_Comp_Bonus(void);
s32 Check_Time_Over(void);
s32 Bonus_Cut_Sub(void);
void Flash_Bonus_Perfect(void);
s32 Check_Bonus_Perfect(void);
s32 Check_Disp_Combo(void);
void Check_Naming(s16 PL_id);
void Clear_1Stage_Work(void);
void Disp_Bonus_Perfect(void);
void FBI_Warning(void);
void FBI_Warning_1st(void);
void FBI_Warning_2nd(void);
s32 Update_BI_Term(void);
void Game_Manage_12_4(void);
void Game_Manage_12_8(void);
void Game_Manage_10th(void);
void Game_Manage_11th(void);
void Game_Manage_12_0(void);
void Game_Manage_12_1(void);
void Game_Manage_12_2(void);
s32 Game_Manage_12_3(void);
s32 Game_Manage_12_7(void);
void Game_Manage_12th(void);
void Game_Manage_1st(void);
void Game_Manage_2_0(void);
void Game_Manage_2_1(void);
void Game_Manage_2_2(void);
void Game_Manage_2_3(void);
void Game_Manage_2_4(void);
void Game_Manage_2nd(void);
void Game_Manage_3rd(void);
void Game_Manage_4th(void);
void Game_Manage_5_0(void);
void Game_Manage_5_1(void);
void Game_Manage_5_2(void);
void Game_Manage_5_3(void);
void Game_Manage_5_4(void);
void Game_Manage_5_5(void);
void Game_Manage_5_6(void);
void Game_Manage_5_7(void);
void Game_Manage_5th(void);
s32 Game_Manage_6th(void);
void Game_Manage_7_0(void);
void Game_Manage_7_1(void);
void Game_Manage_7_2(void);
void Game_Manage_7_3(void);
void Game_Manage_7_4(void);
void Game_Manage_7_5(void);
s32 Game_Manage_7_6(void);
void Game_Manage_7_7(void);
void Game_Manage_7_8(void);
void Game_Manage_7_9(void);
void Game_Manage_7th(void);
void Game_Manage_81_0(void);
void Game_Manage_81_1(void);
void Game_Manage_81_2(void);
void Game_Manage_81_3(void);
void Game_Manage_8_0(void);
void Game_Manage_8_1(void);
void Game_Manage_8_2(void);
s32 Game_Manage_8_3(void);
void Game_Manage_8th(void);
void Game_Manage_9th(void);
s32 Game_Management(void);
void Pool_Score(s16 PL_id);
u32 Setup_Final_Score(s16 Type);
void Setup_Win_Mark(void);
void request_center_message_p2_Manage(s16 Kind_of_Message);
void setFinishType(void);
void Game_Manage_12_5(void);
void Ck_Win_Record(void);
void Erase_Win_Record(s16 PL_id);
void Disp_Win_Record_Sub(s16 PL_id);
void Disp_Win_Record(void);
void BGM_Control(void);
void BGM_Fade_Sub(void);
s32 Check_BI_Grade(s16 PL_id);
s32 Check_Ending();
u32 Check_Ending_Sub(void);
void Disp_Winner(void);
s32 Judge_Next_Disposal(void);
void Check_Perfect(s16 PL_id);
void Quick_Entry(void);
s32 Check_Entry_Again(void);
void Loser_Sub(void);
void Be_Continue(void);
void Update_VS_Data(void);
void Check_Fade_Out_BGM(s16 code);
void Control_Music_Fade(s16 time);
void complete_victory_pause(void);
s32 Check_Break_Into_CPU(s16 PL_id);
void Check_Stage_BGM(void);
s32 Check_Disp_Winner(void);
void Judge_Winner(void);
s32 Setup_BGM_Fade_In(u8 time);
void Update_Level_Control(void);
void request_center_message(s16 Kind_of_Message);

#endif
