#ifndef SYS_TEST_H
#define SYS_TEST_H

#include "structs.h"

void Bg_On_W(u16 s_prm);
void Bg_Off_W();
u32 simmram_large_page_addr(void);
u32 simmram_small_page_addr(void);
void Scrn_Pos_Init(void);
void Scrn_Move_Set_R(s32 n, s16 x, s16 y);
void Scrn_X_Set_R();
void Scrn_Y_Set_R();
void Scrn_Move_Set();
void Scrn_X_Set_W(s32 ix, s16 x);
void Scrn_Y_Set_W(s32 ix, s16 y);
void Scrn_Move_Add(s32 n, s32 dx, s32 dy);
s32 iotest_input_page(void);
s32 iotest_output_page(void);
void soundtest_draw_title(void);
s32 soundtest_page(void);
void colortest_draw_title(void);
s32 colortest_page(void);
s32 screentest_page(void);
void gamedata_show_counters(void);
s32 gamedata_page(void);
s16 config_menu_page(void);
void memtest_sram(void);
s32 cd_check_disc_id(void);
void simm_check_run(void);
void memtest_menu_init(void);
void memtest_menu_select(void);
s32 memtest_page(void);
u8 sram_read_byte(u32 addr);
void sram_write_byte(u32 addr, u8 v);
void sram_bus_slow(void);
void sram_bus_normal(void);
u32 simm_full_checksum(s32 rom, s32 wide);
s32 simm_bank_checksum(s32 slot, s32 count);
void rewrite_cd_not_ready(void);
void coin_work_init(void);
void coin_lock_release(s8 chute);
void coin_lock_set();
void coin_lock_check(s8 chute, s8 coil);
s32 credit_use(s8 n);
void switch_read(s8 mode);
void ext_switch_read(void);
void coin_sw_sample(void);
void gamedata_draw_title(void);
void gamedata_clear_card_counter(void);
void gamedata_print_counters(void);
void coin_chutes_update(s32 keep);
u8 coin_chute_check(s8 n, s32 keep);
void coin_credit_add(s8 n, s8 m);
void coin_counter_drive(s8 n);
void memtest_work_ram(void);
void memtest_memory_check(void);
void memtest_sprite_ram(void);
void memtest_character_ram(void);
void memtest_simm_quick(void);
s32 simm_quick_checksum(s32 slot, s32 mode);
void memtest_ss_ram(void);
void memtest_color_ram(void);
void memtest_eeprom(void);
void memtest_cdrom(void);
s32 rewrite_page(void);
void rewrite_menu_init(void);
void rewrite_menu_select(void);
s32 cd_check_drive_inquiry(void);
void clear_scroll_layer_state_and_mask(void);
void colortest_draw_palette_grid(void);
void scrn_linescroll_set_now(u16 n, void* p);
void scrn_linescroll_set();
void iotest_draw_sw_grid(void);
void iotest_output_toggle(void);
void soundtest_print_lr_balance(s32 x, s32 y, s32 l, s32 r);
void soundtest_print_level_bar(s32 x, s32 y, s32 level);
void soundtest_print_pan_bar(s32 x, s32 y, s32 pan);
u32 memtest_pattern_word(volatile u16* addr, u32 size);
u16 * memtest_pattern_byte_lane(u16 *start, u32 size);
u32 memtest_pattern_masked_word(volatile u16* addr, u32 size);
u32 memtest_pattern_stride_8(volatile u16* addr, u32 size);
void switch_work_clear(char level);
void dispenser_init(void);
void screentest_draw_crosshatch(void);
void scroll_layer_commit(void);
void scrn_line_set_now();
void scrn_line_set(u16 n, s16 v);
void scroll_layer_mask_disable();
void scroll_layer_mask_enable();
void scroll_layers_finalize_frame(void);
s32 scsi_decode_sense_key(s32 status);
s32 scsi_inquiry(s32 len, s32 lun, u8* buf);
s32 scsi_prevent_allow_medium_removal(s32 prevent, s32 lun);
s32 scsi_read_10(s32 lba, s32 count, s32 blk, s32 unused, void* buf);
s32 scsi_read_capacity(s32 len, void* buf);
s32 scsi_request_sense(s32 len, s32 lun, u8* buf);
s32 scsi_send_cdb_and_read(s32 lba, u8* buf);
s32 scsi_send_cdb_bytes(s32 n, s8* cdb);
s32 scsi_start_stop_unit(s32 start, s32 immed);
s32 scsi_test_unit_ready(s32 lun);
void scrn_attr_set();
void scrn_map_set();
void scrn_map_set_now();
void soundtest_monitor_task(void);
void soundtest_code_select(void);
void Irl_Family(void);
void scrn_flip_set(u16 n, u16 flip);
void scrn_flip_toggle(u16 n, u16 flip);
void service_coin_check(void);
void coin_lockout_update(void);
void switch_read_six_button(void);
void coin_sw_shift(void);
void dispenser_sw_read(void);
void dispenser_control(void);

#endif
