#ifndef WORK_H
#define WORK_H

#include "structs.h"

extern s32 (*const decode_chcmd[125])();
extern s32 (*const decode_if_lever[16])();
extern const u16 xcopy_filter_se_table[608];
extern s32 (*const Passive_AS_tbl[21])(PLW* wk);
extern s32 (*const Passive_A_tbl[21])(PLW* wk);
extern s32 (*const Passive_BS_tbl[21])(PLW* wk);
extern s32 (*const Passive_B_tbl[21])(PLW* wk);
extern s32 (*const Passive_CS_tbl[21])(PLW* wk);
extern s32 (*const Passive_D_tbl[21])(PLW* wk);
extern const s16 cmb_pos_tbl[2][2][21];
extern const s16 cmb_window_move_tbl[7];
extern const s16 cmb_window_time_tbl[7];
extern const u32 combo_score_tbl[16][2];
extern const s16 eff25_data_0000[16];
extern const s8 eff94_2000_1_tbl[16];
extern s16 frwctr_min;
extern const s16 pl17_0_00[12];
extern const u8 Coin_Message_Data[7][2];
extern const u8 ttk_damage_req_tbl[83];
extern s16 ID;
extern u32 omop_spmv_ng_table[2];
extern u32 omop_spmv_ng_table2[2];
extern u16 vital_inc_timer;
extern u16 vital_dec_timer;
extern s8 vib_sel[2];
extern char no_sa[2];
extern const u8 * cjdr_hits_table[20];
extern const u8 * cjdr_defense_table[20];
extern void (*const plpdm_xxxxx[39])(PLW* wk);
extern const RANK_DATA Score_Ranking_Table[20];
extern const struct _SAVE_W Game_Default_Data;
extern const CHAR_INIT_ROM char_init_data[];
extern u8 cst_write[2];
extern u8 cst_read[2];
extern s16 score_calc[2][12];
extern u8 end_flag[2];
extern s16 hit_num;
extern s8 paring_attack[2];
extern s8 rever_attack[2];
extern s8 first_attack;
extern s8 cmb_stock[2];
extern s16 old_cmb_flag[2];
extern MultiTexture mts[24];
extern const s16 stg_dum_data_tbl[1];
extern const u8 Rewrite_Color_Data_08[2][13][2];
extern const s16 eff11_data_tbl[24];
extern void (*const EFF42_Jmp_Tbl[5])();
extern MessageData Message_Data[4];
extern void (*const EFF74_Jmp_Tbl[5])();
extern const u32 ake_color[13];
extern s16 exec_tm[8];
extern s16 tail_ix[8];
extern s16 frwctr;
extern s16 frwque[128];
extern const s16 koishi_area_hosei[5];
extern struct _TASK task[11];
extern s8 sa_pa_flag;
extern u8 Disp_Bonus_Contents;
extern u8 bios_region_code;
extern u8 bios_cd_flags;
extern s8 Coin_Mode;
extern s8 Chute_Mode;
extern s8 Sound_Mode;
extern s8 Win_Point_Com;
extern s8 Win_Point_Human;
extern s8 Win_Point_Com_Max;
extern s8 Win_Point_Human_Max;
extern s8 Win_Point_Com_Min;
extern s8 Win_Point_Human_Min;
extern s8 Win_Point_Split;
extern s8 Cabinet_Type;
extern s8 Area_Type;
extern s8 Area_Alt_Flag;
extern s8 Two_Coin_Start;
extern s8 Free_Play_Enable;
extern s8 Cd_Error_Flag;
extern s16 Config_No_0;
extern s16 Config_No_1;
extern s16 Config_No_2;
extern const char * reg_name_tbl[];
extern s32 task_stack_num;
extern u32 frt_tick_count;          /* provisional name */
extern u32* isp_vblank;             /* provisional name */
extern u32* isp_sprite_poly;        /* provisional name */
extern u32* isp_irq_spare;          /* provisional name */
extern u32* isp_exception;          /* provisional name */
extern u32* isp_frt_compare;        /* provisional name */
extern u32* isp_frt_overflow;       /* provisional name */
extern u32 task_sched_context[3];   /* provisional name */
extern u32 exception_regs[23];      /* provisional name */
extern u32 exception_code;          /* provisional name */
extern s32 errno;
extern u32 sys_cfg_default_tbl[];
extern u8 * game_cfg_default_tbl[];
extern s8 Monitor_Flip_Old;
extern const FOLLOW_MENU_1ST* Follow_Menu_1st_Unit_Data[13];
extern const FOLLOW_MENU_2ND* Follow_Menu_2nd_Unit_Data[13];
extern TMSCRIPT gcfg_guide_scr_jp[1];
extern TMSCRIPT gcfg_exit_guide_scr_jp[1];
extern TMSCRIPT gcfg_screen_scr_jp[2];
extern TMSCRIPT gcfg_round_scr_jp[4];
extern TMSCRIPT gcfg_event_scr_jp[2];
extern TMSCRIPT gcfg_bonus_scr_jp[2];
extern TMSCRIPT gcfg_cursor_scr_jp[1];
extern TMSCRIPT gcfg_cursor_clr_scr_jp[1];
extern TMSCRIPT gcfg_gauge_scr_jp[8];
extern TMSCRIPT gcfg_gauge_clr_scr_jp[1];
extern TMSCRIPT gcfg_title_scr_jp[1];
extern TM_STRING gcfg_screen_str_en[2];
extern TM_STRING gcfg_round_str_en[4];
extern TM_STRING gcfg_event_str_en[2];
extern TM_STRING gcfg_bonus_str_en[2];
extern const char * dbg_sign_str[2];
extern const s16 dbg_rgb_preset_tbl[8][3];
extern const TM_STRING dbg_obj_info_str[];
extern const TM_STRING dbg_obj_rel_str[];
extern const TM_STRING dbg_all_char_str[];
extern const TM_STRING dbg_edit_num_str[];
extern const TM_STRING dbg_parts_info_str[];
extern const TM_STRING dbg_hit_size_str[];
extern const TM_STRING dbg_hit_part_str[];
extern const TM_STRING dbg_work_empty_str[];
extern const TM_STRING dbg_blank4_str[];
extern const TM_STRING dbg_exit_ok_str[];
extern const TM_STRING dbg_cg_head_str[];
extern const TM_STRING dbg_cg_att_str[];
extern const TM_STRING dbg_cg_rival_str[];
extern const TM_STRING dbg_cgd_info_str[];
extern const TM_STRING dbg_att_data_str[];
extern const TM_STRING dbg_hud_clr_str[];
extern const TM_STRING dbg_hud_clr_mid_str[];
extern const TM_STRING dbg_hud_clr_low_str[];
extern const TM_STRING dbg_hud_clr_bottom_str[];
extern const TM_STRING dbg_cm_label_str[];
extern const TM_STRING dbg_cgd_type_str[];
extern const TM_STRING dbg_pat_status_str[];
extern const TM_STRING dbg_extdat_str[];
extern const TM_STRING dbg_eftype_names[];
extern const TM_STRING dbg_eftype_s_str[];
extern const TM_STRING dbg_eftype_usemj_str[];
extern const TM_STRING dbg_cancel_on_str[];
extern const TM_STRING dbg_cancel_off_str[];
extern const TM_STRING dbg_koc_cmlp_str[];
extern const TM_STRING dbg_koc_cml2_str[];
extern const TM_STRING dbg_koc_cmsw_str[];
extern const TM_STRING dbg_koc_cmja_str[];
extern const TM_STRING dbg_koc_cmoa_str[];
extern const TM_STRING dbg_waza_kind_str[];
extern TM_STRING dbg_bg_name_str[];
extern const TM_STRING dbg_char_name_str[];
extern const TM_STRING dbg_act_kind_str[];
extern const TM_STRING * dbg_act_name_tbl[];
extern void (*chk_move_jp[28])();
extern void * pl_CMD[];
extern const_s16_arr * player_cmd[];
extern s16 lvr_chk_tbl[4];
extern void (*ta_move_tbl[22])();
extern void (*scr_x_mv_jp[])();
extern char ake_attr_tbl[];
extern const u32 bg_map_tbl2[][3];
extern HUD_CELL * bg_rewrite_cell_tbl[][3];
extern TILEREQ * bg_etc_cell_tbl[][3];
extern s16 op_104_sound[8];
extern void (*end_main_jp[20])(s16);
extern const u32 end_map_tbl[];
extern const PANEL * end_400_panel_tbl[2];
extern void (*end_401_jp[5])();
extern s8 end_5_bg1_cell[4];
extern s16 staff_name_ptr;
extern s32 staffroll_end;
extern u16 scrfont_view_attr;
extern const u16* vital_npos_tbl[2];
extern const u16* vital_attr_tbl[3];
extern const u16 * spgauge_postbl[2];
extern u32 fade_adrs_tbl[];
extern const u16 * stngauge_postbl[2];
extern const s16 * scr_obj_data[];
extern const s16 * scr_obj_data6[];
extern void (*eff09_tbl[28])(WORK_Other*);
extern const s16 * scr_obj_data10[];
extern const s16 * scr_obj_data12[];
extern const s16 * scr_obj_data18[][4];
extern void (*eff18_jp_tbl[])(WORK_Other*);
extern const s16 * eff21_data_adrs[1];
extern const s16 * scr_obj_data25[1];
extern void (*eff25_jp_tbl[10])(WORK_Other* ewk);
extern void (*eff26_jp_tbl[6])(WORK_Other*);
extern const s16 * scr_obj_data26[1];
extern const s16 * scr_obj_data27[2];
extern void (*eff27_jp_tbl[11])(WORK_Other*);
extern const s16 * scr_obj_data28[];
extern const s16 * scr_obj_data44[];
extern void (*eff64_jp_tbl[])(WORK_Other*);
extern void (*eff66_jp_tbl[])(WORK_Other*);
extern const s16 * scr_obj_data87[][4];
extern const s16 * scr_obj_data88[][4];
extern const EFFA6_MESSAGE * effA6_mes_jp[];
extern const EFFA6_MESSAGE * effA6_mes_en[];
extern const EFFA6_MESSAGE * effA6_mes_es[];
extern const EFFA6_MESSAGE * effA6_mes_pt[];
extern const EFFB8_MESSAGE * effB8_mes_jp[];
extern const EFFB8_MESSAGE * effB8_mes_en[];
extern const EFFB8_MESSAGE * effB8_mes_es[];
extern const EFFB8_MESSAGE * effB8_mes_pt[];
extern u32 * ag_char_table[];
extern const EFFF9_MESSAGE * effF9_mes_jp[];
extern const EFFF9_MESSAGE * effF9_mes_en[];
extern const EFFF9_MESSAGE * effF9_mes_es[];
extern const EFFF9_MESSAGE * effF9_mes_pt[];
extern s32 * txt_no_tbl[20];
extern s16 * effH7_move_tbl[];
extern const ColorCode * pl00_cctbl[7][2];
extern const s16 * effL8_data_tbl[];
extern const s16 (*effM4_dir_tbl[])[2];
extern const TM_STRING test_menu_str[];
extern const TM_STRING test_menu_str_asia[];
extern const TMSCRIPT test_menu_scr_jp[];
extern TMSCRIPT sys_cfg_page_scr_jp[];
extern TMSCRIPT sys_cfg_exit_guide_jp[];
extern TMSCRIPT sys_cfg_item_guide_jp[];
extern TMSCRIPT cfg_top_guide_jp[];
extern TMSCRIPT cfg_top_reset_guide_jp[];
extern const u8 * cjdr_blocking_table[20];
extern u16 * metamor_color_ptr_tbl[];
extern s16 iotest_in_no;
extern s16 iotest_out_no;
extern s16 soundtest_rep_timer;
extern s16 soundtest_code;
extern s16 soundtest_no;
extern s16 colortest_no;
extern s16 screentest_no;
extern s16 backup_test_no;
extern s16 config_menu_no;
extern s8 * simm_name_tbl[];
extern s16 memtest_error;
extern s16 memtest_wait;
extern s16 memtest_cursor;
extern s16 memtest_no;
extern s16 rewrite_no;
extern s16 rewrite_cursor;
extern s8 credit_1p;
extern s8 credit_2p;
extern s8 credit_3p;
extern s8 credit_4p;
extern u8 coin_in_flag;
extern u8 coin_out_latch;
extern COINCHUTE * coin_chute_tbl[4];
extern void * coin_sw_tbl[4][2];
extern s8 * credit_ptr_tbl[4];
extern s8 * coin_count_ptr_tbl[4];
extern s32 card_empty_flag;
extern u32 bookkeep_add[4];
extern s8 event_off_flag;
extern const TM_STRING * coin_setting_str_tbl[];
extern const TM_STRING * chute_mode_str_tbl[];
extern const TM_STRING * on_off_str_tbl[];
extern const TM_STRING * sound_mode_str_tbl[];
extern const TM_STRING * monitor_str_tbl[];
extern void (*config_top_item_tbl[])(void);
extern void (*sysconfig_item_tbl[])(void);
extern void (*sysconfig_item_tbl_b[])(void);
extern void (*sysconfig_item_card_tbl[])(void);
extern void (*sysconfig_item_tbl_c[])(void);
extern void (*sysconfig_item_card_tbl2[])(void);
extern u16 sprite_dummy_code;
extern u16 sprite_head_x;
extern u16 sprite_head_y;
extern u16 sprite_pad_x;
extern u16 sprite_pad_y;
extern u32 poly_buf_offset;
extern s32 poly_cram_bank;
extern s32 task_sys_w1;
extern s32 task_sys_w2;
extern s32 task_sys_w3;
extern s32 task_free_count;
extern u32 system_timer;
extern u32 task_tick_mask;
extern s8 system_ctrl_flag;
extern s8 task_tick_mode;
extern s8 vsync_flag;
extern u32 frame_pass_count;
extern s8 task_ran_flag;
extern u8 task_stack[][1024];
extern TASK_QUEUE task_req_queue;
extern u8 task_req_buff[];
extern s16 test_rno;
extern s16 test_menu_no;
extern s16 test_cursor;
extern s16 test_cursor_on;
extern s16 test_cursor_off;
extern s16 test_font_type;
extern s16 test_cursor_max;
extern s16 screen_window[2][4];
extern s16 screen_disp_ctrl;
extern s16 screen_base_x;
extern s16 screen_base_y;
extern s32 screen_mode;
extern u8 zoom_req_flag;
extern u8 window_req_flag;
extern s16 zoom_adj_x;
extern s16 zoom_adj_y;
extern s16 flip_obj_ofs_x;
extern s16 flip_obj_ofs_y;
extern s16 flip_crt_ofs_x;
extern s16 flip_crt_ofs_y;
extern s16 flip_scr_ofs_x;
extern s16 flip_scr_ofs_y;
extern s16 flip_zoom_ofs_x;
extern s16 flip_zoom_ofs_y;
extern s8 Lv;
extern s8 Rnd;
extern s8 PASSIVE_X;
extern WORK * q_hit_push[32];
extern HS hs[32];
extern s8 ca_check_flag;
extern s16 * dmdat_adrs[16];
extern s16 mkm_wk[32];
extern s16 hpq_in;
extern s16 EXE_flag;
extern s16 SLOW_flag;
extern s16 SLOW_timer;
extern u16 * wipe_dst_ptr;
extern u8 * wipe_back_ptr;
extern u8 * wipe_pat_top;
extern u8 * wipe_pat_ptr;
extern u8 Candidate_Buff[16];
extern GradeData judge_item[2][2];
extern GradeFinalData judge_final[2][2];
extern JudgeGals judge_gals[2];
extern JudgeCom judge_com[2];
extern u8 ji_sat[2][384];
extern s16 Game_pause;
extern s16 Game_difficulty;
extern s16 Control_Time;
extern s16 Time_in_Time;
extern s16 Counter_hi;
extern s16 Round_Level;
extern u16 Round_Result;
extern s8 request_message;
extern s8 Winner_id;
extern s8 Loser_id;
extern s16 PL_Wins[2];
extern s8 Break_Into;
extern u8 My_char[2];
extern s8 Super_Arts[2];
extern s8 Fade_Flag;
extern s8 Forbid_Break;
extern s8 Request_Break[2];
extern s16 Fade_R_No0;
extern s16 Fade_R_No1;
extern u8 Fade_Mode;
extern u32 Score[2][3];
extern s16 Play_Type;
extern u8 Play_Type_low;
extern s8 Personal_Continue_Flag[2];
extern s8 Personal_Disp_Flag;
extern s8 WINNER;
extern s8 LOSER;
extern s16 Conclusion_Type;
extern s16 win_type[2][4];
extern s8 win_pause_go;
extern s16 message_index;
extern s16 Conclusion_Flag;
extern s8 New_Challenger;
extern s8 Champion;
extern s8 Complete_Judgement;
extern s8 Perfect_Flag;
extern s16 Fade_Gap_Timer;
extern s8 Fade_Half_Flag;
extern u32 Vital_Bonus[2];
extern u32 Time_Bonus[2];
extern s16 win_mark_new[2];
extern s8 Next_Step;
extern s8 judge_flag;
extern u8 sc_chr_ram[];
extern u8 bcount_mark_chr_w[];
extern s8 Cover_Timer;
extern s16 Text_Page_Y;
extern s8 E_07_Flag[2];
extern s8 Personal_Timer[2];
extern s8 Request_E_No;
extern s8 Request_G_No;
extern s16 G_Timer;
extern s16 G_No[4];
extern s16 D_Timer;
extern s16 D_No[4];
extern u8 Present_Rank[2];
extern s8 Rank_In[2][4];
extern s8 Request_Disp_Rank[2][4];
extern s8 Rank_Demo_Loop;
extern s8 Rank_Type;
extern s8 Flash_Rank_Time;
extern s8 Flash_Rank_Interval;
extern s8 Rank;
extern s8 Rank_X;
extern s16 Rank_Pos_X;
extern s16 Rank_Pos_Y;
extern s16 E_Timer;
extern s16 E_No[4];
extern s16 F_No0[2];
extern s16 F_No1[2];
extern s16 F_No2[2];
extern s16 F_Timer[2];
extern s16 E_Number[2][4];
extern s16 ENTRY_X;
extern s16 C_Timer;
extern s16 C_No[4];
extern s8 Complete_Victory;
extern s8 Demo_Flag;
extern s8 Demo_Stage_Index;
extern s16 S_Timer;
extern s16 S_No;
extern s16 S_Sub_No;
extern s16 S_Sub2_No;
extern s16 S_Sub3_No;
extern s16 Flash_Complete[2];
extern s16 Sel_PL_Complete[2];
extern s16 Sel_Arts_Complete[2];
extern s16 Select_Start[2];
extern s16 Cursor_X[2];
extern s16 Arts_Y[2];
extern s16 Cursor_Y_Pos[][3];
extern s16 Stop_Cursor[2];
extern s16 Move_Super_Arts[2];
extern s16 Battle_Country;
extern s16 Face_Status;
extern s8 Face_MV_Request;
extern s8 Face_Move;
extern s8 Appear_Cursor;
extern s8 Select_Timer;
extern s8 Time_Stop;
extern s8 Time_Over;
extern s16 Unit_Of_Timer;
extern s8 Player_id;
extern s8 Last_Player_id;
extern s8 Player_Number;
extern s8 COM_id;
extern s8 EM_id;
extern s16 Plate_X[2][3];
extern s16 Plate_Y[2][3];
extern s16 SP_No[2][4];
extern s16 Sel_Sub_No[2];
extern s16 Arts_Cursor_No[2];
extern s16 Arts_Cursor_Timer[2];
extern s16 Exit_No;
extern s16 Select_Arts[2];
extern s8 Select_Status[2];
extern s8 Select_Demo_Index;
extern u8 Country;
extern s16 mes_already;
extern s16 CP_No[2][4];
extern s16 CP_Index[2][8];
extern u16 Pattern_Index[2];
extern s16 Timer_00[2];
extern s16 Timer_01[2];
extern s8 Combo_Speed[2];
extern s16 PL_Distance[2];
extern s16 Area_Number[2];
extern u16 Lever_Buff[2];
extern u16 Lever_Pool[2];
extern const_s16_arr Tech_Address[2];
extern s16 Tech_Index[2];
extern s16 Random_ix16_com;
extern s16 Random_ix32_com;
extern s16 M_Timer;
extern s16 VS_Tech[2];
extern s8 Exec_Wipe;
extern u16 Guard_Type[2];
extern s16 Separate_Area[2][3];
extern u32 * Shell_Address[2];
extern u16 Free_Lever[2];
extern s8 Passive_Flag[2];
extern s8 Flip_Flag[2];
extern s8 Lie_Flag[2];
extern s16 Term_No[2];
extern s8 Attack_Flag[2];
extern s8 Passive_Mode;
extern s8 Limited_Flag[2];
extern s8 Shell_Ignore_Timer[2];
extern s16 Com_Width_Data[2];
extern s8 Event_Judge_Gals;
extern u8 EJG_Index[4];
extern s8 Guard_Flag[2];
extern u16 Lever_Squat[2];
extern u16 M_Lv[2];
extern s8 Pierce_Menu[2];
extern s8 Counter_Attack[2];
extern s16 zuubun_base_x;
extern s8 Face_MV_Time;
extern s8 Before_Jump[2];
extern s8 Stop_Combo;
extern u8 Stock_Hit_Flag[2];
extern s8 Rolling_Flag[2];
extern u8 Continue_Coin[2];
extern s16 Cursor_Y[2];
extern s8 Last_Arts_PL;
extern s8 Moving_Plate[2];
extern s8 Naming_Cut[2];
extern s8 Moving_Plate_Counter[2];
extern s8 OK_Priority[2];
extern s8 Player_Color[2];
extern s8 PP_Priority[2][3];
extern u8 Stock_My_char[2];
extern s8 Stock_Player_Color[2];
extern s16 Insert_Y;
extern u8 Version_Type;
extern s8 BGM_Fade_Out_Flag;
extern s16 zoom_request_flag;
extern s16 zoom_request_level;
extern s16 Stock_Com_Color[2];
extern s8 Stock_Com_Arts[2];
extern s8 Stop_SG;
extern s16 Last_Selected_ID;
extern s16 Last_Called_SE;
extern s8 Round_Operator[2];
extern u32 Stock_Score[2];
extern s8 another_bg[2];
extern s8 another_bg_old[2];
extern s8 bg_test_flag;
extern s8 Last_Super_Arts[2];
extern s8 Last_My_char[2];
extern s8 Continue_Menu[2];
extern s8 Timer_Freeze;
extern s8 Rapid_No[2][4];
extern s16 Rapid_Index[2];
extern s8 Standing_Timer[2];
extern s8 Before_Look[2];
extern s16 Shell_Separate_Area[2][3];
extern s16 Attack_Counter[2];
extern s16 Last_Attack_Counter[2];
extern s8 Attack_Count_No0[2];
extern s16 Com_Color_Shot;
extern s8 Standing_Master_Timer[2];
extern s8 No_Death;
extern s8 Flash_MT[2];
extern s8 Squat_Timer[2];
extern s8 Squat_Master_Timer[2];
extern s8 Turn_Over[2];
extern s16 Distance_XX_Index[2];
extern u16 Resume_Lever[2][20];
extern s8 Turn_Over_Timer[2];
extern s8 Jump_Pass_Timer[2][4];
extern s8 sa_gauge_flash[2];
extern s8 Receive_Flag[2];
extern s8 Disposal_Again[2];
extern volatile s8 BGM_Fade_Level;
extern u8 Decided_My_char[2];
extern s8 Break_Com[2][24];
extern s8 Sel_Exit_Flag;
extern u16 Lever_Store[2][3];
extern s16 Return_CP_No[2];
extern s16 Return_CP_Index[2];
extern s16 Return_Pattern_Index[2];
extern s8 aiuchi_flag;
extern u8 paring_counter[2];
extern u8 paring_bonus_r[2];
extern u8 paring_ctr_vs[2][2];
extern u8 paring_ctr_ori[2];
extern u8 Type_of_Attack[2];
extern u16 Lever_LR[2];
extern s16 Last_Eftype[2];
extern u16 DENJIN_No[2];
extern u8 DENJIN_Term[2];
extern u16 SC_Personal_Time[2];
extern u8 Attack_Count_Buff[2][4];
extern u8 Attack_Count_Index[2];
extern s16 Guard_Counter[2];
extern u8 CC_Value[2];
extern u8 Continue_Coin2[2];
extern s16 kage_gfx_ofs[64];
extern s16 kage_gfx_cells[64];
extern s16 car_gfx_ofs[288];
extern s16 car_gfx_cells[288];
extern s16 seraph_gfx_ofs[64];
extern s16 seraph_gfx_cells[64];
extern s16 Limit_Time;
extern u8 Weak_PL;
extern u8 Bullet_No[2];
extern u8 Bullet_Counter[2];
extern s16 Entry_Mes_X[2];
extern s16 Entry_Mes_Wide[2];
extern s8 Disp_Win_Name;
extern u32 Complete_Bonus;
extern s8 Break_Into_CPU;
extern s8 ID_of_Face[3][7];
extern s8 Cursor_Move[2];
extern s8 ID2;
extern s16 Exit_Timer;
extern s8 Introduce_Break_Into[2];
extern u32 Stage_Stock_Score[2];
extern s16 Max_vitality;
extern s8 gouki_wins;
extern s8 EM_Rank;
extern s8 Disp_PERFECT;
extern s8 Deley_Shot_No[2];
extern s8 Deley_Shot_Timer[2];
extern s16 Bonus_Game_Flag;
extern s16 Bonus_Game_Work;
extern s16 Bonus_Game_result;
extern s16 Bonus_Game_ex_result;
extern s8 Lost_Round[2];
extern s8 Super_Arts_Finish[2];
extern s8 Stage_SA_Finish[2];
extern s8 Perfect_Finish[2];
extern s8 Cheap_Finish[2];
extern s8 Last_My_char2[2];
extern u8 gouki_app;
extern s8 Bonus_Game_Complete;
extern s16 Stock_Bonus_Game_Result;
extern s16 Gill_Pos_X;
extern s16 bs_scrrrl[2][2];
extern u32 Final_Bonus_Score;
extern s16 Bonus_Stage_RNO[4];
extern s16 Bonus_Stage_Level;
extern s16 Bonus_Stage_Tix;
extern u8 Combo_Demo_Flag;
extern u8 Stage_Continue[2];
extern u8 Pause_Hit_Marks;
extern u8 Special_Settle;
extern u8 Extra_Break;
extern u8 Shin_Gouki_BGM;
extern s8 Stage_Lost_Round[2];
extern s8 Stage_Perfect_Finish[2];
extern s8 Stage_Cheap_Finish[2];
extern s8 EXE_obroll;
extern u8 End_PL;
extern s8 Stage_Judge_Finish[2];
extern u8 PB_Status;
extern u8 Flip_Counter[2];
extern u8 Bonus_Type;
extern s8 Completion_Bonus[2][2];
extern s8 ichikannkei;
extern s16 bs2_floor[3];
extern s16 bs2_hosei[3];
extern s16 bs2_current_damage;
extern s8 Complete_Face;
extern u8 Plate_Disposal_No[2][3];
extern u8 SO_No[2];
extern u16 Win_Record[2];
extern u16 Stock_Win_Record[2];
extern u8 Disp_Command_Name[2][3];
extern u32 * Synchro_Address[2][2];
extern u8 SC_No[4];
extern s8 Sel_EM_Complete[2];
extern s8 Temporary_EM[2];
extern const u8 * Free_Ptr[2];
extern u8 BGM_No[2];
extern u8 BGM_Timer[2];
extern u16 WGJ_Win;
extern u32 WGJ_Score;
extern u8 EM_History[2][10];
extern u8 Aborigine;
extern u8 Continue_Count_Down[2];
extern u8 WGJ_Target;
extern u8 Final_Result_id;
extern u8 Battle_Round[];
extern u8 Q_Country;
extern u8 Introduce_Boss[2][2];
extern u8 Stage_Intro_Flag;
extern u8 Appear_Q;
extern u32 Bonus_Score_Plus;
extern s8 Cut_Scroll;
extern u32 Perfect_Bonus[2];
extern s8 OK_Moving_SA_Plate[2];
extern u8 Final_Play_Type[2];
extern s8 Cursor_Timer[2];
extern s16 Result_Disp_Timer[2];
extern u8 Reset_Timer[2];
extern s16 scrl;
extern s16 scrr;
extern u8 bbbs_type;
extern u8 Straight_Flag[2];
extern u8 kakushi_on;
extern u8 kakushi_ix;
extern u8 kakushi_op;
extern u8 RO_backup[2];
extern u8 PT_backup;
extern u8 dm17_to_nm23_flag;
extern RANK_DATA Ranking_Data[20];
extern RANK_DATA Present_Data[2];
extern s8 MANAGE_X;
extern s16 Cont_No;
extern s16 Cont_Sub_No;
extern s16 Cont_Sub2_No;
extern s16 Cont_Sub3_No;
extern s16 Cont_Timer;
extern s16 CONTINUE_X;
extern u8 SEL_PL_X;
extern s16 Play_Type_1st;
extern u16 * Demo_Ptr[2];
extern u16 Color7[2];
extern s16 Start_X;
extern s8 Config_Item_jp;
extern s8 Config_Exit_jp;
extern s8 Config_Move_jp;
extern s8 Config_Keep_Bits_jp;
extern s8 Config_Old_jp;
extern s8 Config_New_jp;
extern s8 Config_Org_jp;
extern s16 Config_Attr_jp;
extern s16 Config_Rep_Timer_jp[4];
extern s8 Config_Rep_Count_jp[4];
extern s8 Config_Item_en;
extern s8 Config_Exit_en;
extern s8 Config_Move_en;
extern s8 Config_Keep_Bits_en;
extern s8 Config_Old_en;
extern s8 Config_New_en;
extern s8 Config_Org_en;
extern s16 Config_Attr_en;
extern s16 Config_Rep_Timer_en[4];
extern s8 Config_Rep_Count_en[4];
extern s8 Debug_Tool_No;
extern s16 Debug_Rep_Timer[21];
extern s8 Debug_Rep_Count[21];
extern s16 Debug_RGB[4];
extern s8 Debug_RL_Flag[2];
extern s8 Debug_CG_Flip[2];
extern s8 Debug_Flip_Work[2];
extern s8 Debug_Flip_Mask[2];
extern s8 Debug_Play_Flag;
extern s8 Debug_Snap_Disp;
extern s8 Debug_Dec_Disp;
extern s16 Debug_Rec_Frame;
extern s16 Debug_Rec_Count;
extern s8 Debug_PL_id;
extern s8 Debug_Command;
extern s8 Debug_Edit_Sub;
extern s8 Debug_Hit_Sub;
extern s8 Debug_Box_Edit;
extern s8 dbg_copy_done;
extern s8 dbg_snap_req;
extern s8 dbg_hud_mode;
extern s8 dbg_rec_menu;
extern s8 dbg_save_mode;
extern s8 dbg_look_mode;
extern s8 dbg_kakusyuku_mode;
extern s8 dbg_rec_exist;
extern s8 dbg_cmd_panel;
extern s8 dbg_col_ix[2];
extern s8 dbg_stage_sel;
extern s8 dbg_stage_sub;
extern s16 dbg_judge_eff_ix;
extern s16 dbg_zoom_x;
extern s16 dbg_zoom_y;
extern s16 dbg_old_cgd_type;
extern s16 dbg_hud_x;
extern s16 dbg_copy_pat;
extern s16 dbg_copy_char;
extern u16 dbg_p1sw_0;
extern u16 dbg_p1sw_1;
extern s16 dbg_col_char;
extern s16 dbg_bgcol_ix;
extern u8 dbg_look_judge[];
extern HITA_BOX dbg_look_body[];
extern HITA_BOX dbg_look_hand[];
extern u8 dbg_look_catch[];
extern u8 dbg_look_caught[];
extern HITA_BOX dbg_look_attack[];
extern u8 dbg_look_hosei[];
extern u8 dbg_edit_judge[];
extern u8 dbg_edit_body[];
extern u8 dbg_edit_hand[];
extern u8 dbg_edit_catch[];
extern u8 dbg_edit_caught[];
extern u8 dbg_edit_attack[];
extern u8 dbg_edit_hosei[];
extern u8 dbg_copy_judge[];
extern u8 dbg_copy_body[];
extern u8 dbg_copy_hand[];
extern u8 dbg_copy_catch[];
extern u8 dbg_copy_caught[];
extern u8 dbg_copy_attack[];
extern u8 dbg_copy_hosei[];
extern s16 dbg_hita_num;
extern s16 dbg_hita_grid_sw;
extern s16 dbg_parts_olc_ix[4];
extern s8 dbg_parts_sel;
extern u8 ixbfw_cut;
extern T_PL_LVR t_pl_lvr[2];
extern WAZA_WORK waza_work[2][56];
extern u16 sw_work;
extern s16 * cmd_tbl_ptr;
extern s16 waza_type[2];
extern T_PL_LVR * chk_pl;
extern WAZA_WORK * waza_ptr;
extern WORK_CP wcp[2];
extern s16 cmd_id;
extern PLW * cmd_pl;
extern s16 eff_hit_flag[11];
extern BG bg_w;
extern s16 scr_cg_c_no;
extern s16 ake_cg_c_no;
extern BGW * bgw_ptr;
extern Ideal_W ideal_w;
extern u16 suzi_line_buf[];
extern MVXY bg_mvxy;
extern s16 bg_stop;
extern s8 bg_app_stop;
extern s16 base_y_pos;
extern s16 bg_ofs_work[3];
extern s16 bg_zoom_x_pos;
extern s16 bg_sp_work;
extern s16 bg_land_flag;
extern s8 demo_car_flag[2];
extern s16 bg_etc_flag;
extern s16 bg_stop2;
extern s16 chase_x;
extern s16 chase_y;
extern s16 chase_time_x;
extern s16 chase_time_y;
extern s8 seraph_flag;
extern s8 aku_flag;
extern s8 bg_select_no;
extern s8 bg_app;
extern s16 Name_00[2];
extern SC_NAME_WK * nsc_ptr;
extern RANK_NAME_W rank_name_w[2];
extern s16 Name_Input_f;
extern s16 naming_cnt[2];
extern s16 n_disp_flag;
extern s16 name_limit_timer[2];
extern s16 Appear_end;
extern s16 poison_flag[2];
extern s16 win_rno[2];
extern s16 a_rno;
extern s16 win_free[2];
extern s16 lose_rno[3];
extern s16 lose_free[2];
extern OP_W op_w;
extern s16 op_obj_disp;
extern s8 op_scrn_end;
extern END_W end_w;
extern s8 end_etc_flag;
extern s8 ending_all_end;
extern s8 end_fade_flag;
extern s8 end_no_cut;
extern s16 end_fade_timer;
extern s8 end_name_cut[2];
extern s8 end_staff_flag;
extern u8 end_cont_coin;
extern u8 end_obj_sync;
extern s16 staff_roll_timer;
extern s32 staff_r_no;
extern s8 end5_col_ix;
extern s8 end5_pal_ix;
extern s16 end5_bg1_pos;
extern s16 card_msg_cnt;
extern s16 cd_ready_flag;
extern s16 cd_spin_timer;
extern s16 roll_rate2;
extern s16 roll_rate_t2;
extern s16 roll_stop;
extern s16 name_timer;
extern s8 dbg_play12_w[4];
extern s32 col_trans_result;
extern u8 * sc_bak_ptr;
extern u16 sc_trans_word;
extern u8 sc_chr_bak_1p[];
extern u8 sc_chr_bak_2p[];
extern s16 vital_col_ix;
extern s16 vital_dot_pos;
extern s16 vital_red_ofs;
extern s16 vital_yel_ofs;
extern u16 vital_stop_flag[2];
extern u16 gauge_stop_flag[2];
extern s16 flash_timer;
extern s8 flash_r_num;
extern s8 flash_col;
extern s8 Old_Stop_SG;
extern s8 Exec_Wipe_F;
extern s8 time_clear[2];
extern s16 spg_number;
extern s16 spg_work;
extern s16 spg_offset;
extern s8 time_num;
extern s8 time_timer;
extern s8 time_flag[2];
extern s16 spg_col;
extern s16 win_mark_timer[2];
extern s16 win_mark_phase[2];
extern s16 win_mark_num[2];
extern s16 win_mark_pos[2];
extern s8 fade_layer_num;
extern s16 fade_cont_rno;
extern s8 fade_end_timer;
extern FADE_LAYER fade_layer[];
extern s16 stn_number;
extern s16 stn_work;
extern s16 stn_offset;
extern s8 bonus_pts[2];
extern u8 sa_kind;
extern s16 calc_hit[2][10];
extern s8 sarts_finish_flag[2];
extern s8 last_hit_time;
extern s16 head_ix[8];
extern E14_WORK eff14_work[10];
extern s16 chk77_flag;
extern u8 OK_Appear79[2];
extern u8 Extra_Counter[2];
extern s16 RND_95;
extern s16 END_OF_95;
extern s16 effa6_pos_x_1p;
extern s16 effa6_pos_y_1p;
extern s16 effa6_pos_z_1p;
extern s16 effa6_pos_x_2p;
extern s16 effa6_pos_y_2p;
extern s16 mmes_already;
extern s16 rf_b2_flag;
extern s16 b2_curr_no;
extern WORK_Other * effb3_oya;
extern s16 test_pl_no;
extern s16 test_mes_no;
extern s16 test_in;
extern s16 old_mes_no2;
extern s16 old_mes_no3;
extern s16 old_mes_no_pl;
extern s16 mes_timer;
extern WORK_Other * oya_p;
extern s16 efff9_suicide;
extern s32 * efff9_txt_no_adrs;
extern u16 * efff9_txt_scene_adrs;
extern s16 efff9_PL_NO;
extern s16 efff9_txt_point;
extern s16 efff9_message;
extern s16 keep_mes_no;
extern s16 roll_rate;
extern s16 roll_rate_t;
extern u32 spmv_ng_save;
extern s16 pcon_rno[4];
extern s16 appear_type;
extern u8 round_slow_flag;
extern u8 pcon_dp_flag;
extern u8 pl_eff_disp_stop;
extern u8 win_sp_flag;
extern char dead_voice_flag;
extern PLW plw[2];
extern SA_WORK super_arts[2];
extern PiyoriType piyori_type[2];
extern ComboType combo_type[2];
extern ComboType remake_power[2];
extern ZanzouTableEntry zanzou_table[2][48];
extern RAMBOD rambod[2];
extern RAMHAN ramhan[2];
extern s8 stop_count[2];
extern u16 metamor_original[64];
extern u16 metamor_original2[64];
extern s16 bcdext;
extern SCRLPOS fm_pos[8];
extern u16 scrn_line_prm[][2];
extern u16 scrn_mode_prm[][2];
extern u16 Screen_Switch;
extern u16 Screen_Switch_Buffer;
extern u8 Screen_Switch_Req;
extern s16 iotest_out1_flag;
extern s16 iotest_out2_flag;
extern s32 iotest_hold_flag;
extern s16 iotest_save_flip;
extern u8 iotest_save_flip_low;
extern u32 scsi_sense_key;
extern u32 scsi_sense_asc;
extern s8 scsi_sense_buf[];
extern u8 scsi_mode_buf[];
extern u32 scsi_capacity_buf[2];
extern s8 scsi_toc_buf[];
extern s8 cd_sector_buf[];
extern s32 scsi_error;
extern s8 coin_chute1_w[];
extern s8 coin_chute2_w[];
extern u8 coin3_coin_rate;
extern u8 coin3_credit_rate;
extern u8 coin3_in_flag;
extern u8 coin4_coin_rate;
extern u8 coin4_credit_rate;
extern u8 coin4_in_flag;
extern u16 p1sw_0;
extern u16 p1sw_1;
extern u16 p2sw_0;
extern u16 p2sw_1;
extern u16 p3sw_0;
extern u16 p3sw_1;
extern u16 p4sw_0;
extern u16 p4sw_1;
extern u8 syssw_0;
extern u8 syssw_1;
extern u16 exsw_0;
extern u16 exsw_1;
extern u16 exsw_2;
extern u16 exsw_3;
extern u16 exsw_4;
extern u16 exsw_5;
extern u16 exsw_6;
extern u16 exsw_7;
extern u16 card_sw_0;
extern u16 card_sw_1;
extern u16 coin_sw_hist[];
extern u16 coin_sw_now[4];
extern s16 card_out_req;
extern u16 eep_dummy;
extern u16 eep_strobe_0;
extern u16 eep_strobe_1;
extern u16 eep_strobe_2;
extern u16 eeprom_test_save[64];
extern u8 eeprom_saved_flip;
extern u8 eeprom_game_cfg[];
extern u8 eeprom_backup_cfg[];
extern s16 eeprom_retry;
extern s8 cfg_top_cursor;
extern s8 cfg_coin;
extern s8 cfg_continue;
extern s8 cfg_chute;
extern s8 cfg_sound_mode;
extern s8 cfg_demo_sound;
extern s8 cfg_flip_old;
extern s8 cfg_free_play;
extern s8 cfg_coin_special;
extern s8 cfg_cont_forced;
extern s8 cfg_changed;
extern s8 cfg_voice;
extern s8 cfg_dispenser;
extern s8 cfg_win_point;
extern s8 cfg_win_point_vs;
extern s8 cfg_extra;
extern s8 cfg_cursor;
extern s8 cfg_cursor_old;
extern s8 cfg_coin_step;
extern s8 cfg_coin_sel;
extern s8 cfg_reserve;
extern s32 cfg_item_max;
extern s32 frame_ready;
extern u8 spr_bank;
extern s8 spr_list_ready;
extern s16 simm40_owner[];
extern s16 simm40_link[];
extern s16 simm40_used[];
extern s16 simm10_owner[];
extern s16 simm10_link[];
extern s16 simm10_used[];
extern s32 poly_dma_state;
extern s16 poly_reserve0;
extern s16 poly_reserve1;
extern POLY_LINE poly_line_buf[2][0x155];
extern u32 poly_line_rd[2];
extern u32 poly_quad_rd[2];
extern u32 poly_order_pos[2];
extern SPRITE_LIST sprite_list_w[4];
extern u16 num_font_code;
extern SNDRAMP se_pan_ramp[16];
extern s16 voice_state_init_pair_work;
extern u16 snd_wave_bias;
extern SOUND_CTRL snd_ctrl;
extern u32 bgm_tick_step;
extern u32 se_tick_step[16];
extern s8 sound_sample_submit_work4;
extern u8 bgm_master_vol;
extern u8 snd_master_vol;
extern u8 snd_stereo;
extern u8 gSeqStatus[1];
extern SNDRAMP se_ramp_req;
extern u16 snd_reg_save;
extern u16 snd_seq_max;
extern u8 bgm_status_save[16];
extern u8 sound_sample_submit_work7;
extern u8 bgm_master_vol_init;
extern s16 cram_bank_old;
extern s16 cram_bank_now;

extern s8 Monitor_Flip;
extern s8 Continue_Flag;
extern s8 Demo_Sound;
extern s8 Language;
extern s8 Free_Play;
extern u8 Card_Dispenser;
extern s8 Voice_Type;
extern const TM_STRING insert_coin_mes[9];
extern const TM_STRING warning_mes[9][11];
extern u32 * dbg_pl_char_tbl[][9];
extern const u32 bg_map_tbl[][3];
extern const u16 * spgauge_puttbl[2];
extern const u16 * stngauge_puttbl[2];
extern TMSCRIPT * sys_cfg_coin_scr_jp[];
extern TMSCRIPT * sys_cfg_chute_scr_jp[];
extern TMSCRIPT * sys_cfg_continue_scr_jp[];
extern TMSCRIPT * sys_cfg_monitor_scr_jp[];
extern TMSCRIPT * sys_cfg_demo_scr_jp[];
extern TMSCRIPT * sys_cfg_sound_scr_jp[];
extern u8 no_cd_flag;
extern s8 unused_flag_a;
extern s8 unused_flag_b;
extern s8 unused_flag_c;
extern u32 bgm_tempo_add;
extern TCB * current_task;
extern SETTINGS game_config_work;
extern TCB task_tbl[8];
extern SCROLL_WINDOW zoom_frame[2];
extern CharGfxSlot cg_slot_tbl[512];
extern CharGfxEntry * cg_data_list;
extern s8 Judge_Round_Flag;
extern s8 Reserve_Cut;
extern s8 Wipe_Count;
extern u8 Wipe_Limit;
extern u8 Wipe_Mode;
extern u8 Wipe_Kind;
extern s16 F_No3[2];
extern s8 Next_Demo;
extern s16 M_No[4];
extern s8 Demo_Step_Flag;
extern s8 Cursor_Y_low[4];
extern s8 judge_disp_all;
extern s8 Keep_BGM_Flag;
extern u16 pcon_timer;
extern u8 CC_Type;
extern s16 hitmark_gfx_ofs[2][512];
extern s16 hitmark_gfx_cells[512];
extern u8 Straight_Counter[2];
extern u8 Escape_SS;
extern u32 Bonus_Score;
extern u8 Demo_Lever_Play;
extern s8 Get_Demo_Index;
extern u8 WIN_X;
extern u8 GO_No[2];
extern u8 Wipe_Panel_Count;
extern u8 Battle_Q[2];
extern s8 Debug_R_No;
extern s8 Debug_Select_No;
extern s8 Debug_Menu_No;
extern u16 dbg_p2sw_0;
extern u16 dbg_p2sw_1;
extern s16 dbg_dipsw_0;
extern s16 dbg_dipsw_1;
extern s16 * dbg_edit_box;
extern PLW * dbg_pl;
extern s16 * dbg_slot;
extern s16 dbg_slot_w[2][9];
extern SNAPSHOT* dbg_snap_ptr;
extern SNAPSHOT dbg_snap_w[2][128];
extern WORK_Other * dbg_ghost_ewk[2][3];
extern s16 dbg_col_no;
extern PATTERN_BUF dbg_look_buf;
extern PATTERN_BUF dbg_copy_buf;
extern PATTERN_BUF dbg_edit_buf;
extern WORK_Other_JUDGE * dbg_judge_ewk;
extern WORK_Other * dbg_hita_ewk[7];
extern PLW dbg_parts_plw[4];
extern AKE_SCRL ake_scrl_w[5];
extern s8 bg_vbl_trans_flag;
extern BG_ADRS eff_bg_adrs[3];
extern s16 bg1403_wait;
extern SELPL card_pl_w[2];
extern u16 * sc_trans_dst;
extern u8 * sc_trans_src;
extern VITAL_BAR vit_bar[2];
extern COUNT_WORK count_work;
extern s16 win_mark_rno[2];
extern STN_DAT sdat[2];
extern CMST_WIN cmst_buff[2][4];
extern SCRLPOS scrn_pos[5];
extern SCROLL_CTRL scrn_reg_w[4];
extern SPRPTR scrn_map_ptr[];
extern s16 scsi_cdb_len;
extern u16 card_out_busy;
extern u32 book_coin_count[4];
extern u8 eeprom_w[128];
extern SETTINGS Game_setting;
extern SPRITE_ENTRY spr_entry_a[512];
extern SPRITE_ENTRY spr_entry_b[512];
extern SPRITE_ENTRY * spr_prio_a[0x80];
extern SPRITE_ENTRY * spr_prio_b[0x80];
extern u16 spr_entry_cnt[5][2];
extern u32 poly_line_cnt[2];
extern POLYCMD poly_quad_buf[2][32];
extern u32 poly_quad_cnt[2];
extern u16 poly_order_kind[2][0x175];
extern s32 poly_wr_bank;
extern s32 poly_rd_bank;
extern const u16 * snd_attack_ptr;
extern const u16 * snd_decay_ptr;
extern const u16 * snd_lfo_rate_ptr;
extern const u16 * snd_pitch_lfo_ptr;
extern const u16 * snd_vol_lfo_ptr;
extern SNDSAMPLE * snd_sample_tbl;
extern u8 ** snd_bank_tbl;
extern u32 snd_fade_level;
extern u32 snd_fade_speed;
extern SNDVOICE bgm_voice[16];
extern SNDVOICE se_voice[16];
extern u32 * snd_seq_data;
extern u8 Allow_a_battle_f;
extern s8 Appear_car_stop[2];
extern s8 Appear_flag[2];
extern s8 Appear_free[2];
extern s8 Appear_hv[2];
extern s8 Continue_Count[2];
extern u8 Continue_Cut[2];
extern s16 DE_X[19];
extern u8 EM_Candidate[2][2][10];
extern u8 EM_List[2][2];
extern s16 Face_No[2];
extern s8 Flash_Sign[2];
extern u16 Game_timer;
extern s8 Ignore_Entry[2];
extern s8 Last_Selected_EM[2];
extern s16 Offset_BG_X[6];
extern s8 Operator_Status[2];
extern u8 Order[100];
extern u8 Order_Dir[100];
extern u8 Order_Timer[100];
extern u8 Round_num;
extern u8 SEL_CPU_X;
extern u8 Scene_Cut;
extern s8 Suicide[8];
extern s16 Target_BG_X[6];
extern s16 VS_Index[2];
extern s16 app_counter[2];
extern s16 appear_work[2];
extern const BBBSTable * bbbs_table[2][5];
extern const u16 chain_hidou_nm_air_table[8];
extern const u16 chain_hidou_nm_ground_table[8];
extern const u16 chain_normal_air_table[8];
extern const u16 chain_normal_ground_table[8];
extern u32 * char_add[22];
extern const u8 * cjdr_karaburi_table[20];
extern s8 cmb_all_stock[1];
extern s8 cmb_calc_now[2];
extern ConstShortArray eff48_adrs_tbl[22];
extern u32 frw[128][512];
extern const s16 ** kizetsu_timer_table[9];
extern NAME_WK * name_ptr;
extern NAME_WK name_wk[2];
extern const u8 plpat_rno_filter[16];
extern SC_NAME_WK sc_name_wk[2][4];
extern const s16 smoke_check[22];
extern SPG_DAT spg_dat[2];
extern u8 test_flag;

extern void (*Name_Jmp_scs[8])();
extern void (*opening_move_jp[19])();
extern const s16 * flash_obj_data61[];
extern const s16 * eff86_adrs_tbl[];
extern s16 Counter_low;
extern u16 Fade_Number;
extern s8 Ranking_X;
extern s8 Demo_PL_Index;
extern s16 zoom_req_flag_old;
extern s16 scr_req_x;
extern s16 scr_req_y;
extern s16 Last_Pattern_Index[2];
extern u8 Perfect_Counter[];
extern s8 Auto_Cursor[2];
extern s8 Auto_No[2];
extern s8 Auto_Index[2];
extern s8 Auto_Timer[2];
extern u8 Explosion;
extern s8 Stage_Time_Finish[2];
extern s8 Best_Grade[2];
extern s8 akebono_flag;
extern s16 op_end_flag;
extern s16 op_sound_status;
extern OPBW * opw_ptr;
extern s16 op_plmove_timer;
extern s16 op_demo_index;
extern MVXY op_bg_mvxy[3];
extern ROUND_TIMER round_timer;
extern const TM_STRING dbg_menu_str[15];
extern const TM_STRING dbg_select_exit_str[2];
extern const TM_STRING dbg_rec_menu_str[3];
extern const TM_STRING dbg_rec_clear_str[3];
extern const TM_STRING dbg_rec_nodata_str[2];
extern void (*end_400_jp[5])();
extern void (*end_402_jp[5])();
extern const TMSCRIPT config_top_scr_jp[];
extern int (*config_menu_tbl[2])();
extern u32 (*config_page_tbl[3])();
extern u32 (*config_top_step_tbl[2])();
extern int (*sysconfig_step_tbl[2])();
extern u32 spr_pool_busy;
extern s8 test_sw_lock;
extern s16 Random_ix16_ex_com;
extern u16 Random_ix32_ex_com;
extern s32 suzi_calc_w[2];
extern s16 ls_cnt1;
extern s16 ls_rate1;
extern u8 col_trans_req_tbl[256];
extern s16 col_trans_req_cnt[3];
extern u32 palette_base;

/* Records of these arrays are reached the way the game computes their offset: with shifts and adds,
 * cut to 16 bits (u8 for the second index of judge_item). */
#define WCP(x) (*(WORK_CP*)((u8*)wcp + (s16)(((x) << 10) + ((x) << 2) + ((x) << 1))))
#define WAZA(x, j) (*(WAZA_WORK*)((u8*)waza_work + (s16)(((x) << 10) + ((x) << 9) + ((x) << 5)) + (s16)(((j) << 5) - ((j) << 2))))
#define PLAYER(x) (*(PLW*)((u8*)plw + (s16)(((x) << 10) + ((x) << 7) + ((x) << 4) + ((x) << 3))))
#define JUDGE_ITEM(x, j) (*(GradeData*)((u8*)judge_item + ((s16)(((x) << 7) + ((x) << 4) + ((x) << 3))) + ((u8)(((j) << 6) + ((j) << 3) + ((j) << 2)))))
#define JUDGE_FINAL(x, j) (*(GradeFinalData*)((u8*)judge_final + ((s16)(((x) << 8) + ((x) << 6) + ((x) << 4) + ((x) << 3))) + ((s16)(((j) << 7) + ((j) << 5) + ((j) << 3) + ((j) << 2)))))
#define CMST(x, j) (*(CMST_WIN_R*)((u8*)cmst_buff + (u8)((x) * 112) + (s8)(((j) << 5) - ((j) << 2))))
#define SE_VOICE(x) (*(SNDVOICE*)((u8*)se_voice + (s16)((x) * sizeof(SNDVOICE))))
/* Per-use record offsets the way the arcade computes them (muls.w, then sts macl). SHC r26 schedules
   `sts macl` with no dependency on the multiply; the read lands after it only when the product goes
   back into the register that held the multiplicand, which a single s16 `ofs = n; ofs *= size`
   gives (macl_check.py proves each use). WCP_OFS(ofs, n) sets the offset, WCP_AT(ofs) is the record,
   WCP_MUL(ofs, n) does both in one expression (one use per full expression). */
#define WCP_OFS(ofs, n) ((ofs) = (n), (ofs) *= (s16)sizeof(WORK_CP))
#define WCP_AT(ofs) (*(WORK_CP*)((u8*)wcp + (ofs)))
#define WCP_MUL(ofs, n) WCP_AT((WCP_OFS(ofs, n), (ofs)))
#define PL_CMD_NUM(x) ((const s16*)((const u8*)pl_cmd_num + (s16)(((x) << 4) - ((x) << 1))))
#define CMB_POS(mode, pl, k) (*(const s16*)((u8*)cmb_pos_tbl + (u8)(((mode) << 6) + ((mode) << 4) + ((mode) << 2)) + (s8)(((pl) << 5) + ((pl) << 3) + ((pl) << 1)) + (k) * 2))

#endif
